# Introduction to Dionysius "the Perigete"


- he is an epic poet (verb ἀείδειν, poet speaking at first person lines 1--3; the addresses the Muses, line 62)

But his content strictly follows the conventional order of a geographic treatise.

1. 




Latin xlations:

- Rufius Festus Avieniush
- Priscian. 

Commentary by Eustathius

ID'ed in acrostic disc'ed 1884

Suda delta 1173

Διονύσιος,  ̓Αλεξανδρεύς, ὁ Γλαύκου υἱός, γραμματικός: ὅστις ἀπὸ Νέρωνος συνη̂ν καὶ τοι̂ς μέχρι Τραϊανου̂ καὶ τω̂ν βιβλιοθηκω̂ν προὔστη καὶ ἐπὶ τω̂ν ἐπιστολω̂ν καὶ πρεσβειω̂ν ἐγένετο καὶ ἀποκριμάτων. ἠ̂ν δὲ καὶ διδάσκαλος Παρθενίου του̂ γραμματικου̂, μαθητὴς δὲ Χαιρήμονος του̂ φιλοσόφου, ὃν καὶ διεδέξατο ἐν  ̓Αλεξανδρείᾳ.

## Reading

The ToposText web site has an English translation  (Yumna Khan, 2002) and Greek text of Dionysius [here](https://topostext.org/work/201).


The Scaife Library has a Greek text of Dionysius [here](https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0084.tlg001.1st1K-grc1:).