# Selections from Dionysius of Alexandria


:::: {.columns}

::: {.column width="60%"}
`1` Ἀρχόμενος γαῖάν τε καὶ εὐρέα πόντον **ἀείδειν**
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
**ἀείδειν** The verb identifies this as the song of an epic poet.
:::

::::

:::: {.columns}

::: {.column width="60%"}
`2` καὶ ποταμοὺς πόλιάς τε καὶ ἀνδρῶν ἄκριτα φῦλα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`3` μνήσομαι Ὠκεανοῖο βαθυρρόου· ἐν γὰρ ἐκείνῳ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`4` πᾶσα χθὼν, ἅτε νῆσος ἀπείριτος, ἐστεφάνωται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`5` οὐ μὲν πᾶσα διαπρὸ περίδρομος, ἀλλὰ διαμφὶς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`6` ὀξυτέρη βεβαυῖα πρὸς ἠελίοιο κελεύθους,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`7` σφενδόνῃ εἰοικυῖα· μίαν δέ ἑ καίπερ ἐοῦσαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`8` ἄνθρωποι τρισσῇσιν ἐπ’ ἠπείροισι δάσαντο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`9` πρώτην μέν Λιβύην, μετὰ δʼ Εὐρώπην Ἀσίην τε.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`10` Ἀλλʼ ἤτοι Λιβύη μὲν ἀπʼ Εὐρώπης ἔχει οὖρον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`11` λοξὸν ἐπὶ γραμμῆσι, Γάδειρά τε καὶ στόμα Νείλου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`12` ἔνθα βορειότατος πέλεται μυχὸς Λλγύλπτοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`13` καὶ τέμενος περίπυστον Ἀμυκλαίοιο Κανώβου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`14` Εὐρώπην δʼ Ἀσίης Τάναϊς διὰ μέσσον ὁρίζει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`15` ὅς ῥά θʼ ἑλισσόμενος γαίης διὰ Σαυροματάων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`16` σύρεται ἐς Σκυθίην τε καὶ ἐς Μαιώτιδα λίμνην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`17` πρὸς βορέην· νότιον δὲ μεσούριον Ἑλλήσποντος·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`18` σῆμα δ ὑπερτέταται νοτιώτερον ἐς στόμα Νείλου·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`19` Ἄλλοι δʼ ἠπείροισι διὰ χθόνα νοσφίζουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`20` Ἰσθμὸς ἄνω τέταταί τις ὑπέρτατος Ἀσίδος αἴης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`21` Κασπίης τε μεσηγὺ καὶ Εὐξείνοιο Οκλάσσης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`22` κεῖνον δ Εὐρώπης Ἀσίης θ ὅρον ηὐδάξαντο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`23` ἄλλος δʼ αὖ μακρὸς καὶ ἀθέσφατος ἐς νότον ἕρπει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`24` Ἀραβίου κόλποιο καὶ Αἰγύπτοιο μεσηγὺ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`25` ὅς ῥά τε νοσφίζει Λιβύην Ἀσιήτιδος αἴης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`26` Τοῖα μὲν ἀμφʼ οὔροισι βροτοὶ διεφημίξαντο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`27` πάντη δʼ ἀκαμάτου φέρεται ῥόος Ὠκεανοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`28` εἷς μὲν ἐὼν, πολλῇσι δʼ ἐπωνυμίῃσιν ἀρηρώς·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`29` ἤτοι ὁ μὲν Λοκροῖο παρʼ ἐσχατιὴν ζεφύροιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`30` Ἄτλας ἑσπέριος κικλήσκεται, αὐτὰρ ὕπερθεν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`31` πρὸς βορέην, ἵνα παῖδες ἀρειμανέων Ἀριμασπῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`32` πόντον μιν καλέουσι πεπηγότα τε Κρόνιόν τε·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`33` ἄλλοι δʼ αὖ καὶ νεκρὸν ἐφήμισαν εἵνεκ’ ἀφαυροῦ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`34` ἠελίου· βράδιον γὰρ ὑπεὶρ ἔλα τήνδε φαείνει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`35` αἰεὶ δὲ σκιερῇσι παχύνεται ἐν νεφέλῃσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`36` αὐτὰρ ὅθι πρώτιστα φαείνεται ἀνθρώποισιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`37` ἠῷον καλέουσι καὶ Ἰνδικὸν οἶδμα θαλάσσης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`38` ἄγχι δʼ Ἐρυθραῖόν τε καὶ Αἰθόπιον καλέουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`39` πρὸς νότον· ἔνθα δὲ πολλὸς ἀοικήτου χθονὸς αὐλὼν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`40` ἐκτέταται, μαλεροῖσι κεκαυμένος ἠελίοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`41` Οὕτως Ὠκεανὸς περιδέδρομε γαῖαν ἅπασαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`42` τοῖος ἐὼν καὶ τοῖα μετʼ ἀνδράσιν οὐνόμαθʼ ἕλκων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`43` Κόλπους δἔνθακαὶ ἔνθʼ ἀπερεύγεται,εῖς ἅλα βάλλων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`44` ἔνδοθι· τυτθοὺς μὲν πλέονας, πίσυρας δὲ μεγίστους·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`45` ἤτοι μὲν πρώτιστον, ὅς ἑσπερίην ἅλα τίκτει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`46` συρόμενος Λιβύηθεν ἔσω Παμφυλίδος αἴης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`47` δεύτερον αὖτ· ὀλίγον μὲν, ἀτὰρ προφερέστατον ἄλλων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`48` ἀποκιδνάμενος Κρονίης ἁλὸς ἐκ βορέαο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`49` ὅς τ Κασπίη αἰπὺ ῥέεθρον ἐπιπροΐησι θαλάσσῃ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`50` ἥντε καὶ Ὑρκανίην ἕτεροι διεφημίξαντο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`51` Τῶν δʼ ἄλλων, οἵτ’ εἰσὶν ἀπαὶ νοτίης ἁλὸς ἄμφω,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`52` εἶςμὲν ἀνώτερόςἐστι,τὸ Περσικὸν οἶδμαπροχεύων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`53` ἀντία Κασπίης τετραμμένος ἀμφιτρίτης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`54` ἄλλος δʼ Ἀράβιος κυμαίνεται ἔνδοθι κόλπος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`55` Εὐξείνου πόντου νοτιώτερον ὁλκὸν ἑλίσσων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`56` Τόσσοι μὲν κόλποι βαθυκύμονος Ὠκεανοῖο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`57` οἱ μείζους· ἄλλοι δέ τ ἀπειρέσιοι γεγάασιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`58` νῦν δʼ ἁλὸς ἑσπερίης ἐρέω πόρον, ἥτʼ ἐπὶ πάσας
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`59` ἠπείρους λοξοῖσιν ἐπιστρέφεται πελάγεσσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`60` ἄλλοτε μὲν νήσοισι περίδρομος, ἄλλοτε δʼ οὖτε
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`61` ἢ ὀρέων ἢ πέζαν ὑποξύουσα πολήων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`62` Ὑμεῖς δ , Μοῦσαι, σκολιὰς ἐνέποιτε κελεύθους,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`63` ἀρξάμεναι **στοιχηδὸν** ἀφʼ ἑσπέρου Ὠκεανοῖο·
:::

::: {.column width="10%"}
**στοιχηδὸν**

Cf στίχος as term for a line of hexameter.
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`64` ἔνθα τε καὶ στῆλαι περὶ τέρμασιν Ἡρακλῆος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`65` ἑστᾶσιν, μέγα θαῦμα, παρʼ ἐσχατόωντα Γάδειρα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`66` μακρὸν ὑπὸ πρηῶνα πολυσπερέων Ἀτλάντων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`67` ἦχί τε καὶ χάλκειος ἐς οὐρανὸν ἔδραμε κίων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`68` ἠλίβατος, πυκινοῖσι καλυπτόμενος νεφέεσσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`69` Πόντος μὲν πρώτιστος Ἰβηρικὸς ἀρχομένοισιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`70` ἐγκέχυται, ὅσπερ τε καὶ Εὐρώπης πέλει ἀρχὴ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`71` καὶ Λιβύης· μέσσος γὰρ ἐλίσσεται ἀμφοτεράων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`72` Στῆλαι δʼ ἔνθα καὶ ἔνθα παρὰ πλευρῇσι κέονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`73` ἡ μὲν ἐπʼ Εὐρώπην, ἡ δʼ ἐς Λιβύην δρόωσα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`74` Τὸν δέ μετεκδέχεται Γαλάτης ῥόος, ἔνθα τε γαῖα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`75` Μασσαλίη τετάνυσται, ἐπίστροφον ὅρμον ἔχουσα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`76` Ἑξείης δʼ ἐπὶ τοῖσι Λιγυστιὰς ἕλκεται ἄλμη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`77` ἐνθʼ Ἰταλῶν υἱῆες ἐπʼ ἠπείροιο νέμονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`78` ἐκ Διὸς Αὐσονιῆες, ἀεὶ μέγα κοιρανέοντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`79` ἀρξάμενοι βορέηθεν ἔσω Λευκὴν ἐπὶ πέτρην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`80` ἥ ῥά τε καὶ Σικελῆς ἐπὶ πορθμίδος ἐρρίζωται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`81` ἑξείης δʼ ἐπὶ Κύρνον ἐρεύγεται ἁλμυρὸν ὕδωρ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`82` Τῇ δʼ ἔπι Σαρδόνιος μορμύρεται ἔνδοθι πόντος·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`83` τὸν δὲ μέτʼ ὠρύεται Τυρσηνίδος οἶδμα θαλάσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`84` πρὸς νότον· αὐτὰρ ἔπειτα πρὸς αὐγὰς ἠελίοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`85` κυρτὸς ἐπιστρέφεται Σικελὸς ῥόος· αὐτὰρ ἔνερθεν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`86` ἐγκέχυται καὶ μέχρι πολυκλύστοιο Παχύνου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`87` καὶ Κρήσσης ἄκρης (ἥτʼ εἰς ἅλα πουλὺ νένευκε,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`88` πάρ θʼ ἱερὴν Γόρτυνα καὶ ἠπειρώτιδα Φαιστόν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`89` προπρηνὴς, Κριοῖο παραυγάζουσα κάρηνον·.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`90` τοὔνεκα καὶ Κριοῦ μιν ἐφημίξαντο μέτωπον)·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`91` ναὶ μὴν καὶ τετάνυσιαι Ἰηπυγίην ἐπὶ γαῖαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`92` Κεῖθεν δʼ εὐρυνθεῖσα τιταίνεται Ἀδριὰς ἅλμη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`93` πρὸς βορέην, αὖθις δὲ πρὸς ἐσπέριον μυχὸν ἕρπει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`94` ἥντε καὶ Ἰονίην περιναιέται ηὐδάξαντο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`95` Δισσὰς δʼ ἠπείρους ἐπερεύγεται· ἐς μέν ἰόντι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`96` δεξιτερὴν κατὰ χεῖρα φαείνεται Ἰλλυρὶς αἶα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`97` Δαλματίη δʼ ἐφύπερθεν, ἐνυαλίων πέδον ἀνδρῶν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`98` σκαιῆ δʼ Αὐσονίων παραπέπταται ἄσπετος ἰσθμός,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`99` πουλυτενὴς, τρισσῇσι περίδρομος ἀμφιτρίτῃς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`100` Τυρσηνῇ Σικελῇ τε καὶ Ἀδριάδι πληθούσῃ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`101` ἡ μία δʼ εἰς ἄνεμον τεκμαίρεται ὁλκὸν ἑκάστη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`102` Τυρσηνὴ ζέφυρον, Σικελὴ νότον, Ἀδριὰς εὖρον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`103` Αὐτὰρ ὑπὲρ Σικελῆς χθονὸς ἕλκεται οἶδμα κορύσσων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`104` Λιβύης,νοτίην περὶ Σύρτιν ἑλίσσων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`105` τὴν ἑτέρην, ἥνπερ τε καὶ εὐρυτέρην ἐνέπουσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`106` ἄλλη δ, τις ἀφαυρὸν ἔχει πόρον, ἔνδον ἐοῦσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`107` τηλόθεν ἐρχομένην δέχεται πλημμύριδα πόντου.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`108` Ὣς οἱ μὲν βοόωσιν ἑλισσόμενοι δύο κόλποι·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`109` ἐκ δὲ ῥόων Σικελῶν Κρήτης ἀναπέπταται οἶδμα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`110` μακρὸν ἐπ’ ἀντολίην Σαλμωνίδος ἄχρι καρήνου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`111` ἣν Κρήτης ἐνέπουσιν ἑώϊον ἔμμεναι ἄκρην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`112` **Δ**οιαὶ δʼ ἑξείης προτέρω φρίσσουσι θάλασσαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`113` **Ἰ**σμαρικοῦ πνοιῇσιν ἐλαυνόμεναι βορέαο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`114` **ὀ**ρθὸν φυσιόωντος, ἐπεὶ κατεναντία κεῖνται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`115` **ν**αῦται δὲ πρώτην Φαρίην ἅλα κικλήσκουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`116` **ὕ**στατον ἐς πρηῶνα τιταινομένην Κασίοιο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`117` **Σ**ιδονίην δʼ ἑτέρην, ὅθι τείνεται ἐς μυχὰ γαίῃς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`118` **Ἰ**σσοῦ ἄχρι πτόλιος, Κιλίκων χώρην παραμείβων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`119` **Ἰ**σσικὸς ἑλκόμενος βορέην ἔπι κόλπος ἀπείρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`120` **ο**ὐ μὲν πολλὸν ἄνευθεν ἰσόδρομος· ἄγχι γὰρ ἤδη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`121` **ὕ**σπληγγι δνοφερῇ Κιλίκων ἀποπαύεται αἴης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`122` τῆμος ἐπὶ ζέφυρον στρεπτὴν ἐπερεύγεται ἅλμην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`123` Ὡς δὲ δράκων βλοσυρωπὸς ἑλίσσεται, ἀγκύλος ἕρπων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`124` νωθὴς τῷ δ ὕποπᾶσα βαρύνεταιοὔρεος ἄκρη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`125` ἐρχομένῳ· τὼς κεῖνος ἐλίσσεται εἰν ἁλὶ κόλπος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`126` νήχυτος, ἔνθα καὶ ἔνθα βαρυνόμενος προχοῇσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`127` Τοῦ μὲν ἐπὶ προχοῇ Παμφύλιοι ἀμφινέμονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`128` ὅσσον ἐπιπροβέβηκε Χελιδονίων μυχὰ νήσων·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`129` σῆμα δʼ ἔχει ζεφύρου Παταρηίδα τηλόθεν ἄκρην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`130` Φράζεο δʼ, ἐκ κείνου τετραμμένος αὖθις ἐπʼ ἄρκτους
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`131` Αἰγαίου πόντοιο πλατὺν πόρον, ἔνθα τε κῦμα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`132` ῥησσόμενον νήσοισι περιβρέμεται Σποράδεσσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`133` οὐ γάρ τις κείνῳ ἐναλίγκια κύματʼ ὀφέλλει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`134` ὑψόθι μορμύρων, ἕτερος πόρος ἀμφιτρίτης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`135` οὖρον δʼ ἐς Τένεδον τεκμαίρεται ἐσχατόωσαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`136` Ἴμβρον ἔχων ἑτέρωθεν,ὅθεν στενὸς ἔρχεται αὐλών,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`137` συρόμενος βορέηνδε Προποντίδος ἔνδοθι πάσης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`138` Τῆς δʼ ὅπερ ἄσπετα φῦλα τιταίνεται Ἀσίδος αἴης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`139` πρὸς νότον· ἠπείρου γὰρ ἐπὶ πλατὺς ἔρχεται ἰσθμός.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`140` Τῇ δʼἔπι Θρηικίου στόμα Βοσπόρου, ὃν πάρος Ἰώ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`141` Ἥρης ἐννεσίῃσιν ἐνήξατο, πόρτις ἐοῦσα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`142` Στεινότατος δὴ κεῖνος ἀπάντων ἔπλετο πορθμὸς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`143` τῶν ἄλλων, οἵτʼ εἰσὶ πολυκλύστοιο θαλάσσης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`144` Κυανέας ὅθι μῦθος ἀναιδέας εἰν ἁλὶ πέτρας
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`145` πλαζομένας καναχηδὸν ἐπʼ ἀλλήλῃσι φέρεσθαι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`146` Ἐκ δὲ τοῦ οἰγόμενος παραπέπταται ἀνδράσι Πόντος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`147` πολλὸς ἐὼν καὶ πολλὸν ἐπʼ ἀντολίης μυχὸν ἕρπων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`148` Τοῦ δʼ ἤτοι λοξαὶ μέν ἐπιτροχάουσι κέλευθοι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`149` αἰεὶ πρὸς βορέην τε καὶ ἀντολίην ἁρόωσαι·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`150` μέσσαι δʼ ἔνθα καὶ ἔνθα δύω ἀνέχουσι κολῶναι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`151` ἡ μὲν ὑπερνοτίη; τήν τε κλείουσι Κάραμβιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`152` ἡ δὲ βορειοτέρη γαίης ὑπὲρ Εὐρωπείης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`153` τήν ῥα περικτίονες Κριοῦ καλέουσι μέτωπον·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`154` αἵτʼ ἄμφω ξυνίασιν ἐναντίαι, οὐ μὲν ἐοῦσαι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`155` ἐγγύθεν, ἀλλ ὅσον ὁλκὰς ἐπὶ τρίτον ἦμαρ ἀνύσσαι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`156` Ἐκ τοῦ δʼ ἂν καὶ Πόντον ἴδοις διθάλασσον ἐόντα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`157` τόρνῳ ἐειδόμενον περιηγέος ἅμματι τόξου·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`158` ἀλλʼ εἴη νευρῆς σημήια δεξιὰ Πόντου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`159` ἰθὺ διαγραφθέντα, μόνη δέ τοί ἐστι Κάραμβις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`160` γραμμῆς ἐκτὸς ἐοῦσα καὶ ἐς βορέην ὁρόωσα·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`161` σῆμα δʼ ἔχει κεράων σκαιὸς πόρος, ὅστ’ ἐπὶ δισσὴν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`162` εἱλεῖται στροφάλιγγα, βιοῦ κεράεσσιν ἐοικώς.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`163` Τοῦ καὶ πρὸς βορέην Μαιώτιδος ὕδατα λίμνης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`164` ἐγκέχυται. Τῇ μέν τε πέρι Σκύθαι ἀμφινέμονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`165` ἄνδρες ἀπειρέσιοι, καλέουσι δὲ μητέρα Πόντου·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`166` ἐκ τῆς γὰρ Πόντοιο τὸ μυρίον ἕλκεται ὕδωρ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`167` ὀρθὸν Κιμμερίου διὰ Βοσπόρου, ᾧ ἔνι πολλοὶ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`168` Κιμμέριοι ναίουσιν ὑπὸ ψυχρῷ ποδὶ Ταύρου.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`169` Τοίη μὲν μορφὴ κυαναυγέος ἀμφιτρίτης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`170` νῦν δέ τοι ἠπείρου μυθήσομαι εἶδος ἁπάσης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`171` ὄρρα καὶ οὐκ ἐςιδών περ ἔχοις εὔφραστον ὀπωπήν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`172` ἐκ τοῦ δʼ ἂν γεραρός τε καὶ αἱδοιέστερος εἴης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`173` ἀνδρὶ παρʼ ἀγνώσσοντι πιφαυσκόμενος τὰ ἕκαστα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`174` Ἤτοι μὲν Λιβύη τετανυσμένη ἐς νότον ἕρπει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`175` ἐς νότον ἀντολίην τε, τραπεζίῳ εἶδος ὁμοίη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`176` ἀρξαμένη πρώτιστα Γαδειρόθεν, ᾗχί περ ἄκρη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`177` ἐζ μοχὸν ὀξονθεῖσα τιταίνεται Ὠκεανοῖο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`178` οὖρον δʼ Ἀραβίης τεκμαίρεται ἄγχι θαλάσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`179` εὐρύτερον· τόθι γαῖα κελαινῶν Αἰθιοπήων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`180` τῶν ἑτέρων, τῶν ἄγχι τιταίνεται οὖδας Ἐρεμβῶν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`181` παρδαλέῃ δέ μιν ἄνδρες ἐπικλείουσιν ὁμοίην·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`182` ἦ γὰρ διψηρή τε καὶ αὐχμήεσσα τέτυκται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`183` τῇ καὶ τῇ κυανῇσι κατάστικτος φολίδεσσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`184` ἀλλʼ ἤτοι πυμάτην μὲν ἐπὶ γλωχῖνα νέμονται φῦλα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`185` ἀγχοῦ στηλάων Μαυρουσίδος ἔθνεα γαίης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`186` Τοῖσι δʼ ἔπι Νομάδων παραπέπταται ἄσπετα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`187` ἔνθα Μασαισύλιοί τε καὶ ἀγρόνομοι Μασυλῆες
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`188` βόσκονται σὺν παισὶν ἀνʼ ἤπειρόν τε καὶ ὕλην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`189` μαιόμενοι βιότοιο κακήν καὶ ἀεικέα θήρην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`190` Οὐ γὰρ γειομόροιο τομὴν ἐδάησαν ἀρότρου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`191` κείνοις δʼ οὔποτε τερπνὸς ἀκούεται ὁλκὸς ἀμάξης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`192` οὐδὲ βοῶν μυκηθμὸς ἐς αὔλιον ἐρχομενάων·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`193` ἀλλʼ αὔτως, ἅτε θῆρες, ἀνὰ δρία βουκολέονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`194` νήιδες ἀσταχύων καὶ ἀπευθέες ἀμήτοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`195` Τοῖς δʼ ἔπι Καρχηδὼν πολυήρατον ἀμπέχει ὅρμον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`196` Καρχηδὼν, Λιβύων μέν, ἀτὰρ πρότερον Φοινίκων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`197` Καρχηδὼν, ἣν μῦθος ὑπαὶ βοῒ μετρηθῆναι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`198` Ἑξείης δʼ ἐπὶ Σύρτις ἀγάρροον ὁλκὸν ἑλίσσει
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`199` βαιοτέρη· μετὰ τὴν δὲ πρὸς αὐγὰς ἕλκεται ἄλη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`200` ἄσπετος, εὐρυτέρησι βαρυνομένη προχοῇσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`201` ἔνθα, κορυσσομένης Τυρσηνίδος ἀμφιτρίτης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`202` ἄλλοτε μὲν πλημμυρὶς ἐγείρεται, ἄλλοτε δʼ αὖτε
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`203` ἄμπωτις ξηρῇσιν ἐπιτροχάει ψαμάθοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`204` Τάων δʼ ἀμφοτέρων μεσάτη πόλις ἐστηρικται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`205` ἥν ῥά τε κικλήσκουσι Νέην πόλιν· ἧς ὑπὲρ αἶαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`206` Λωτοφάγοι ναίουσι, φιλόξεινοι γεγαῶτες
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`207` ἔνθα ποτʼ αἰολόμητις ἀλώμενος ἦλθεν Ὀδυσσύς.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`208` Κεῖνον δ αὖ περὶ χῶρον ἐρημωθέντα μέλαθρα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`209` ἀνδρῶν ἀθρήσειας ἀποφθιμένων Νασαμώνων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`210` οὓς Διὸς οὐκ ἀλέγοντας ἀπώλεσεν Αὐσονὶς αἰχμή.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`211` Ἀσβύσται δʼ ἰπὶ τοῖσι μεσήπειροι τελέθουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`212` καὶ τέμενος Λιβυκοῖο θεοῦ ψαμάθῳ ὑπὸ πολλῇ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`213` Κυρήνη τʼ εὔιππος, Ἀμυκλαίων γένος ἀνδρῶν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`214` ἄγχι δὲ Μαρμαρίδαι προνενευκότες Αἰγύπτοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`215` Γαίτουλοί τʼ ἐφύπερθε καὶ ἀγχίγυοι Νίγρητες.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`216` Ἑξείης δʼ ἐπὶ τοῖσι Φαρούσιοι, ὧν ὑπὲρ αἶαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`217` ναίουσιν Γαράμαντες ἀπείριτοι· ἐν δὲ μυχοῖσι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`218` βόσκοντʼ ἠπείροιο πανύστατοι Αἰθιοπῆες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`219` αὐτῷ ἐπʼ Ὠκεανῷ, πυμάτης παρὰ τέμπεα Κέρνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`220` Τῶν πάρος αἰθαλέων Βλεμύων ἀνέχουσι κολῶναι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`221` ἔνθεν πιοτάτοιο κατέρχεται ὕδατα Νείλου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`222` ὃς δʼ ἤτοι, Λιβύηθεν ἐπ’ ἀντολίην πολὺς ἕρπων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`223` Σῖρις ὑπʼ Αἰθιόπων κικλήσκεται· οἱ δὲ Συήνης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`224` ἐνναίται στρεφθέντα μετ οὔνομα Νεῖλον ἔθεντο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`225` Κεῖθεν δʼ ἐς βορέην τετανυσμένος ἄλλυδις ἄλλος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`226` ἑπτὰ διὰ στομάτων εἱλιγμένος εἰς ἅλα πίπτει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`227` ὕδασι πιαίνων λιπαρὸν πέδον Αἰγύπτοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`228` Οὐ γάρ τις ποταμῶν ἐναλίγκιος ἔπλετο Νείλῳ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`229` οὔτʼ ἰλὺν βαλέειν, οὔτε χθονὸς ὄλβον ἀέξειν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`230` ὅς ῥά τε καὶ Λιβύην ἀποτέμνεται Ἀσίδος αἴης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`231` ἐς λίβα μὲν Λιβύην, ἐς δʼ αὐγὰς Ἀσίδα γαῖαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`232` Τῷ πάρα ναιετάουσιν ἀριπρεπέων γένος ἀνδρῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`233` οΐ πρῶτοι βιότοιο διεστήσαντο κελεύθους,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`234` πρῶτοι δʼ ἱμεροεντος ἐπειρήθησαν ἀρότρου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`235` καὶ σπόρον ἰθυτάτης ὑπὲρ αὔλακος ἁπλώσαντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`236` πρῶτοι δὲ γραμμῇσι πόλον διεμετρήσαντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`237` θυμῷ φρασσάμενοι λοξὸν δρόμον ἠελίοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`238` Τῶν δέ κεν αὐδήσαιμι καὶ αὐτῆς πείρατα γαίης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`239` καὶ μορφήν· οὐ μὲν γὰρ ὀλίζονος ἔμμορε τιμῆς·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`240` οὐδὲ μὲν οὐδʼ ὀλίγη μέγεθος πέλει, ἀλλά τις ἄλλων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`241` εὔβοτος εὐλείμων τε καὶ ἀγλαὰ πάντα φέρουσα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`242` Σχῆμα μὲν οὖν τρισσῇσιν ἐπὶ πλευρῇσι βέβηκεν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`243` εὐρὺ μὲν ἀμφʼ ἀκτὰς βορεήτιδας, ὀξὺ δʼ ἐπʼ ἠ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`244` ἑλκόμενον καὶ μέχρι βαθυκρήμνοιο Συήνης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`245` οὔρεσιν ἀμφοτέροισι περισκεπέεσσιν ἐρυμνόν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`246` τῶν μέσα καλλιρόοιο κατέρχεται ὕδατα Νείλου.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`247` Καὶ τὴν μὲν πολλοί τε καὶ ὄλβιοι ἄνδρες ἔχουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`248` ἠμὲν ὅσοι Θήβην ἐρικυδέα ναιετάουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`249` Θήβην ὠγυγίην, ἑκατόμπυλον, ἔνθα γεγωνὼς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`250` Μέμνων ἀντέλλουσαν ἑὴν ἀσπάζεται Ἠῶ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`251` ὅσσοι θʼ ἑπτάπολιν μεσάτην ἤπειρον ἔχουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`252` ἦδʼ ὅσσοι νοτερῇσιν ἐπʼ ἠιόνεσσι θαλάσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`253` παραλίην ναίουσιν ἔσω Σερβωνίδος ἅλμης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`254` Τῆς πρὸς μὲν ζεφύροιο Μακηδόνιον πτολίεθρον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`255` ἔνθα Σινωπίταο Διὸς μεγάλοιο μέλαθρον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`256` χρυσῷ τιμήεντι κεκασμένον. Οὐκ ἂν ἐκείνου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`257` νηὸν ἐν ἀνθρώποισι θεώτερον ἄλλον ἴδηαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`258` οὐδὲ μὲν ἀφνειὴν ἑτέρην πόλιν, ᾗχί τε μακραί
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`259` φαίνονται σκοπιαὶ Παλληνίδος Εἰδοθεείης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`260` Τὴν δὲ μέτʼ ἀντολίηνδε παραὶ Κασιώτιδα πέτρην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`261` Πηλῆος πτολίεθρον ἐπώνυμον ἄνδρες ἔχουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`262` ἔξοχα ναυτιλίης δεδαημένοι. Οὐ μὲν ἐκεῖνοι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`263` ἀνέρες ἐν Λιβύεσσιν ἀρίθμιοι ἦ γὰρ ἐς αὐγὰς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`264` ἑπταπόρου Νείλοιο νενασμένον ἔλλαχον ἄστυ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`265` ἄλλοι δὲ πλεῖστοι τήνδε χθόνα ναιετάουσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`266` οἱ μὲν ἐπʼ Ὠκεανῷ, οἱ δʼ ἠπείρους ἀνὰ μέσσας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`267` οἱ δʼ ἀμφʼ εὐρείης Τριτωνίδος ὕδατα λίμνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`268` ἥτε μέση Λιβύης ἀμφέλκεται εὐρέα κόλπον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`269` Τοίη μὲν Λιβύης μορφὴ καὶ σχῆμα τέτυκται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`270` εἰ δὲ καὶ Εὐρώπης ἐθέλεις τύπον, οὔ τί σε κεύσω.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`271` Ωὐτὸς μὲν Λιβύης ῥυσμὸς πέλει, ἀλλὰ μετʼ ἄρκτους
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`272` ἔστραπται, καὶ τοῖος ἐπʼ ἀντολίην πάλιν ἕρπει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`273` οἷος καὶ νοτίης Λιβύης ἐπὶ τέρμα βέβηκεν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`274` ἄμφω δʼ ἶσον ἔχουσιν ἐπʼ Ἀσίδα νείατον ἴχνος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`275` ἡ μὲν πρὸς βορέην, ἡ δʼ ἐς νότον. Εἰ δέ κε θείης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`276` ταύτας ἀμφοτέρας γαῖαν μίαν, ἦ κεν ἐπιπρὸ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`277` σχῆμα πέλοι κώνου πλευρῇς ἴσον ἀμφοτέρῃσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`278` ὀξὺ μὲν ἑσπέριον, πλατὺ δʼ ἀντολίην ὑπὸ μέσσην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`279` Τοὔνεκά μοι, τοιοῦτον ἰδὼν πόρον ἀμφοτεράων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`280` ἠπείρων, ῥέα τέρμα κιχήσεαι Εὐρωπείης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`281` Τῆς ἤτοι πυμάτην μὲν ὑπὸ γλωχῖνα νέμονται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`282` ἀγχοῦ στηλάων μεγαθύμων ἔθνος Ἰβήρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`283` μῆκος ἐπʼ ἠπείρου τετραμμένονγᾖχ βόρετίου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`284` Ὠκεανοῦ κέχυται ψυχρὸς ῥόος, ἔνθα Βρετανοὶ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`285` λευκά τε φῦλα νέμονται ἀρειμανέων Γερμανῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`286` Ἑρκυνίου δρυμοῖο παραθρώσκοντες ὀρόγκους.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`287` Ἤπειρον κείνην ἰκέλην ἐνέπουσι βοείῃ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`288` Τοῖς δ ἔπι Πυρηναῖον ὄρος καὶ δώματα Κελτῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`289` ἀγχόθι πηγάων καλλιρρόου Ἠριδανοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`290` οὖ ποτʼ ἐπὶ προχοῇσιν ἐρημαίην ἀνὰ νύκτα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`291` Ἡλιάδες κώκυσαν, ὀδυρόμεναι Φαέθοντα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`292` κεῖθι δὲ Κελτῶν παῖδες, ὑφήμενοι αἰγείροισι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`293` δάκρυʼ ἀμέλγονται χρυσαυγέος ἠλέκτροιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`294` Τὸν δὲ μέθʼ ἑξείης Τυρσηνίδος ἤθεα γαίης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`295` τῆς δὲ πρὸς ἀντολίην ἀναφαίνεται Ἄλπιος ἀρχή,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`296` τῆς διὰ μεσσατίης κατασύρεται ὕδατα Ῥήνου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`297` ὑστάτιον ποτὶ χεῦμα βορειάδος ἀμφιτρίτης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`298` Ῥήνῳ δʼ ἑξιίης ἐπιτέλλεται ἱερὸς Ἴστρος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`299` Ἴστρος, ἐς ἀντολίην τετραμμένος ἄχρι θαλάσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`300` Εὐξείνου, τόθι πᾶσαν ἐρεύγεται ὕδατος ἄχνην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`301` πενταπόροις προχοῇσιν ἑλισσόμενος περὶ Πεύκην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`302` Τοῦ μέν πρὸς βορέην τετανυσμένα φῦλα κέχυνται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`303` πολλὰ μάλʼ ἑξείης Μαιώτιδος ἐς στόμα λίμνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`304` Γερμανοὶ Σαμάται τε Γέται θʼ ἅμα Βαστάρναι τε,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`305` Δακῶν τʼ ἄσπετος αἶα καὶ ἀλκήεντες Ἀλανοί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`306` Ταῦροί θ , οἳ ναίουσιν Ἀχιλλῆος δρόμον αἰπύν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`307` στεινὸν ὁμοῦ δολιχόν τε, καὶ αὐτῆς ἔς στόμα λίμνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`308` Τῶν δʼ ὕπερ ἐκτέταται πολυΐππων φῦλον Ἀγαυῶν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`309` ἔνθα Μελάγχλαινοί τε καὶ ἀνέρες Ἱππημολγοί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`310` Νευροί θʼ Γππόποδές τε Γιλωνοί τ ἠδ Ἀγαθυρεὸις
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`311` ᾗχι Βορυσθένεος ποταμοῦ τετανυσμένον ὕδωρ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`312` μίσγεται Εὐξείνῳ, Κριοῦ προπάροιθε μετώπου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`313` ὀρθὸν ἐπὶ γραμμῇ κατεναντία Κυανεάων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`314` Κεῖθι καὶ Ἀλδήσκοιο καὶ ὕδατα Παντικάπαο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`315` Ῥιπαίοις ἐν ὄρεσσι διάνδυχα μορμύρουσι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`316` Τῶν δὲ παρὰ προχοῇσι πεπηγότος ἐγγύθι πόντου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`317` ἡδυφαὴς ἤλεκτρος ἀέξεται, οἷά τις αὐγὴ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`318` μήνης ἀρχομένης· ἀδάμαντά τε παμφανόωντα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`319` ἐγγύθεν ἀθρήσειας ὑπὸ ψυχροῖς Ἀγαθύρσοις.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`320` Ἴστρου μὲν τοσσοίδε βορειότεροι γεγάασιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`321` πρὸς δὲ νότον Γέρραι καὶ Νωρίκιʼ ἄστεʼ ἐρυμνά,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`322` Παννόνιοι, Μυσοί τε, βορειότεροι Θρηίκων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`323` αὐτοί τε Θρήικες, ἀπείρονα γαῖαν ἔχοντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`324` οἱ μὲν ἐπὶ προβολῇσι Προποντίδος ἀμφιτρίτης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`325` οἱ δ ὑπὲρ Ἑλλήσποντον ἀγάρροον, οἱ δʼ ὑπὲρ αὐτῆς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`326` Αἰγαίης βαθὺ κῦμα πολυφλοίσβοιο θαλάσσης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`327` Ἔνθα μελισσοβότοιο κατὰ σκοπιὰς Παλλήνης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`328` φύεται ἀστέριος καλὸς λίθος, οἷά τις ἀστὴρ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`329` μαρμαίρων, λύχνις τεπυρὸς φλογὶ πάμπαν ὁμοῖος.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`330` Ἴστρον μὲν ποταμὸν τόσσοι περιναιετάουσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`331` φράζεο δʼ Εὐρώπης λοιπὸν πόρον, ὅστ’ ἐπὶ τρισσὴν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`332` ἐκτέταται κρηπῖδα πρὸς ἠῶ, τὴν μὲν Ἰβήρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`333` τὴν δὲ Πανελλήνων, τὴν δʼ ἐσθλῶν Αὐσονιήων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`334` Ἀλλʼ ἤτοι πυμάτη μὲν ἀγαυῶν ἐστιν Ἰβήρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`335` γείτων Ὠκεανοῖο πρὸς ἑσπέρου· ἐν δέ οἱ ἄκμη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`336` στηλάων Ἀλύβη κεῖται μία· τῆς δʼ ὑπένερθεν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`337` Ταρτησὸς χαρίεσσα, ῥυηφενέων πέδον ἀνδρῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`338` Κεμψοί θ , οἳ ναίουσιν ὑπαὶ πόδα Πυρηναῖον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`339` Μέσση δʼ ἀμφοτέρων παραπέπταται Αὐσονὶς αἶα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`340` πουλυτενής· τὴν μέν τε μέσην ὄρος ἄνδυχα τέμνει
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`341` ὀρθὸν, ἅτʼ ἐκ στάθμης ἰθυμμένον· οὐκ ἂν ἐκεῖνο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`342` ἴδρις μωμήσαιτο σοφῆς ὑποεργὸς Ἀθήνης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`343` ὅν ῥά τε κικλήσκουσιν Ἀπέννιον· ἐκ δὲ βορείης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`344` Ἄλπιος ἀρχόμενος Σικελὴν ἐπὶ πορθμίδα λήγει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`345` Πολλὰ δέ οἱ φῦλʼ ἀμφί, τά τοι ῥέα πάντʼ ἀγορεύσω,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`346` ἀρξάμενος πλευρῆς ζεφυρίτιδος ἐκ βορέαο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`347` Τυρσηνοὶ μὲν πρῶτ ,ἐπὶ δέ σφισι φῦλα Πελασγῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`348` οἳ ποτε Κυλλήνηθεν ἐφ’ ἑσπερίην ἅλα βάντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`349` αὐτόθι ναιήσαντο σὺν ἀνδράσι Τυρσηνοῖσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`350` Τοῖς δʼ ἔπι μέρμερον ἔθνος ἀγαυῶν ἐστι Λατίνων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`351` γαῖαν ναιετάοντες ἐπήρατον, ἧς διὰ μέσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`352` Θύμβρις ἑλισσόμενος καθαρὸν ῥόον εἰς ἅλα βάλλει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`353` Θύμβρις ἐϋρρείτης, ποταμῶν βασιλεύτατος ἄλλων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`354` Θύμβρις, ὃς ἱμερτὴν ἀποτέμνεται ἄνδυχα Ῥώμην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`355` Ῥώμην τιμήεσσαν, ἐμῶν μέγαν οἶκον ἀνάκτων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`356` μητέρα πασάων πολίων, ἀφνειὸν ἔδεθλον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`357` Τῇ δʼ ἔπι Καμπανῶν λιπαρὸν πέδον, ᾗχι μέλαθρον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`358` ἁγνῆς Παρθενόπης, σταχύων βεβριθὸς ἀμάλλαις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`359` Παρθενόπης, ἣν πόντος ἑοῖς ὑπεδέξατο κόλποις.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`360` Πρὸς δὲ νότον,μάλα πολλὸν ὑπὲρ Σειρηνίδαπέτρην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`361` φαίνονται προχοαὶ Πευκεντίνου Σιλάροιο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`362` ἄγχι δὲ Λευκανοὶ καὶ Βρέντιοι ἄνδρες ἔασι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`363` τοσσάτιον ναίοντες, ὅσον Λευκὴν ἐπὶ πέτρην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`364` Κεῖθεν δʼ ἐς βορέην Ζεφύρου παραφαίνεται ἄκρη·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`365` τῇ δʼ ὕπο Λοκροὶ ἔασιν, ὅσοι προτέροις ἐτέεσσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`366` ἦλθον ἐπʼ Αὐσονίην, σφετέρης μιχθέντες ἀνάσσῃς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`367` τῶν καὶ νῦν γένος ἐστὶν ἐπὶ προχοῇσιν Ἄληκος.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`368` Τοὺς δὲ μέθʼ ἑξείης Μεταπόντιοι· ἐγγύθι δέ σφεων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`369` ἱμερτὸν πτολίεθρον ἐϋστεφάνοιο Κρότωνος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`370` ναιόμενον χαρίεντος ἐπ’ Αἰσάρου προχοῇσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`371` ἔνθα κεν αἰπὺν ἴδοιο Λακινιάδος δόμον ἽΙρης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`372` Ἔστι δέ τοι κἀκεῖθι, Διὸς μέγα χωσαμένοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`373` δειλαίη Σύβαρις, ναέτας στενάχουσα πεσόντας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`374` μηναμένους ὑπὲρ αἶσαν ἐπʼ Ἀλφειοῦ γεράεσσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`375` Σαυνῖται δʼ ἐπὶ τοῖσι μέσην χθόνα ναιετάουσι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`376` καὶ Μαρσῶν θοὰ φῦλα· Τάρας δʼἁλὸς ἐγγύθιναίει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`377` ἥν ποτʼ Ἀμυκλαίων ἐπολίσσατο καρτερὸς Ἄρης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`378` Ἑξείης δʼ ἐπὶ τοῖσι Καλαβρίδος ἤθεα γαίης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`379` φῦλά τ Ἰηπύγων τετανυσμένα μέσφ Ὑριοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`380` παραλίης Ὑρίου, τόθι σύρεται Ἀδριὰς ἃλμη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`381` πόντον ἐς ἀγχίπορον Ἀκυλήιον· ἔνθα νένασται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`382` ἄστυ Τεγεστραίων, μυχάτοις ἐπὶ πείρασι πόντου.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`383` Τόσσα μὲν Αὐσονίην περιβόσκεται ἔθνεα γαῖαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`384` Κεῖθεν δʼ εἰς αὐγὰς στρεπτὴν ἀπερεύγεται ἅλμην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`385` θῖνας ὑποξύουσα Λιβυρνίδας, ἀμφί τʼ ἐρυμνὴν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`386` Ὑλλήων χθόνα πᾶσαν, ὅση παρακέκλιται ἰσθμῷ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`387` Βουλίνων τ' ἀκταῖς· ἐπὶ δ'ἄσπιτον ὁλκὸν γουσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`388` Ἰλλυρικὴν περὶ χέρσον ἐλίσσεται ἄχρι κολώνης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`389` οὐρέων τʼ ἠλιβάτων, τὰ Κεραύνια κικλήσκουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`390` Κεῖνον δʼ ἂν περὶ κόλπον ἴδοις ἐρικυδέα τύμβον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`391` τύμβον, ὃν Ἁρμονίης Κάδμοιό τε φῆμις ἐνίσπει
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`392` κεῖθι γὰρ εἰς ὀφίων σκολιὸν δέμας ἠλλάξαντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`393` ὁππότ ἀπʼ Ἰσμηνοῦ λιπαρὸν μετὰ γῆρας ἵκοντο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`394` Ἔνθα σφιν τέρας ἄλλο θεοὶ θέσαν· ἀμφὶ γὰρ αἶαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`395` κείνην ἀμφοτέρωθεν ἐρηρέδαται δύο πέτραι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`396` αἵτ’ ἄμφω ξυνίασι δονεύμεναι, εὖτέ τις ἀρχὴλον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`397` γίγνεται ἐνναέτησι κυλινδομένοιο κακοῖο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`398` Πρὸς δὲ νότον,μάλα πολλὸνὑπέρ Θρῄκην ἐρίβω·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`399` Ὡρικίην θʼ ὑπῖρ αΐαν, ἐρείδεται Ἑλλάδος ἀρχή,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`400` πολλὸν ἀνερχομένη, δισσῇ ζωσθεῖσα θαλάσσῃ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`401` Αἰγαίῃ Σικελῇ τʼ ἄνεμον δέ τοι ἔλλαχʼ ἑκάστη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`402` ἑσπέρτον Σικελὴ, τόν τε ζέφυρον καλέουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`403` Αἰγαίη δʼ εὖρον. Πέλοπος δʼ ἐπὶ νῆσος ὀπηδεῖ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`404` εἰδομένη πλατάνοιο μυουρίζοντι πετήλῳ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`405` Ἄκρῳ μὲν γὰρ ἔοικεν ἐεργόμενος στενὸς Ἰσθμὸς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`406` πρὸς βορέην,καὶ ξυνὸν ἐφ’ Ἑλλάδος ἴχνος ἐρείδων·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`407` φύλλῳ δʼ ἤπειρος πολυδινήτῳ περίμετρος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`408` κόλποις εἰναλίοις ἐστεμμένη ἔνθα καὶ ἔνθα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`409` Τῆς μὲν πρὸς ζεφύροιο Τριφυλίδος ἤθεα γαίης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`410` ἔνθʼ ἐρατεινότατος ποταμῶν Ἀλφειὸς ὁδεύει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`411` σχιζόμενος προχοῇσι Μεσηνίου Εὐρώταο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`412` οἵτ’ ἄμφω Ἀσέηθεν ἀναβλύζουσι ῥέεθρα·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`413` ἀλλʼ ὁ μὲν Ἠλείων, ὁ δʼ Ἀμυκλαίων χθόνα τέμνει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`414` Καδδὲ μέσην νῆσον κοίλην χθόνα ναιετάουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`415` Ἀρκάδες Ἀπιδκνῆες ὑπὸ σκοπιὴν Ἐρυμάνθου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`416` ἔνθα Μέλας, ὅθι Κρᾶθις, ἵνα ῥέεὶ ὑγρὸς Ἰάων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`417` ἧχι καὶ ὠγύγιος μηκύνεται ὕδασι Λάδων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`418` Ἀγχοῦ δʼ Ἀργείων ἄροσις καὶ γαῖα Λακώνων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`419` ἡ μὲν ἐς ἀντολίην, ἡ δʼ ἐς νότον εἰσορόωσα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`420` Δοιαὶ δʼ Ἴσθμια νῶτα περιβρομέουσι θάλασσαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`421` ἥ τʼ Ἐφύρης ἀντικρὺ ποτὶ ζόφον, ἥ τε πρὸς αὐγὰς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`422` ἑλκομένη, τὴν μέν τε Σαρωνίδα κικλήσκουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`423` Νέρθε γε μὴν Ἰσθμοῖο πρὸς αὐγὰς Ἀττικὸν οὖδας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`424` τοῦ διὰ θεσπεσίου φέρεται ῥόος Ἰλισσοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`425` ἔνθεν καὶ Βορέης ποτʼ ἀνήρπασεν Ὠρείθυιαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`426` Τῷ δʼ ἔπι Βοιωτῶν τε πέδον καὶ Λοκρὶς ἄρουρα·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`427` Θεσσαλίη δʼ ἐπὶ τοῖσι, Μακηδονίης τε πόληες.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`428` Ταῖς δʼ ἔπι φαίνονται κορυφαὶ χιονώδεος Λἵμου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`429` Θρηικίου· τοῦ δʼ ἄντα ποτὶ ῥιπὴν ζεφύροιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`430` Δωδώνης ἤπειρος ἀπείριτος ἐκτετάνυσται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`431` Τῆς δʼ ὕπερ ἐς νότον εἶσι, μετὰ σκοπιήν Ἀρακύνθου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`432` ἀνδρῶν Αἰτωλῶν πεδίον μέγα· τοῦ διὰ μέσσου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`433` σύρεται ὁλκὸν ἄγων Ἀχελώιος ἀργυροδίνης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`434` Τρινακίης ἐπὶ πόντον ἑλισσόμενος διὰ μέσσων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`435` νήσων, ἃς καλέουσιν Ἐχινάδας, ᾗσιν ὁμούρων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`436` ἕσπεται ἄλλυδις ἄλλα Κεφαλλήνων πτολίεθρα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`437` Τῷ δ ἔπι Φωκὶς ἄρουρα, πρὸς ἀντολίην τε κοὶ ἠῶ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`438` ἑλκομένη βορέηνδε κατὰ στόμα Θερμοπυλάων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`439` Παρνησοῦ νιφόεντος ὑπὸ πτυχί· τῆς διὰ μέσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`440` Κηφισοῦ μέγα χεῦμα κατερχόμενον κελαρύζει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`441` Τῷ πάρα Πυθῶνος θυόεν πέδον, ᾗχι δράκοντος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`442` Δελφύνης τριπόδεσσι θεοῦ παρακέκλιται ὁλκός,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`443` ὁλκός, ἀπειρεσίῃσιν ἐπιφρίσσων φολίδεσσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`444` νηῷ ἐν ἱμερτῷ,τόθι πολλάκις αὐτὸς Ἀπόλλων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`445` ἢ ἀπὸ Μιλήτου ἠὲ Κλάρου ἄρτι βεβηκώς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`446` ἱστάμενος χρυσέης ἀναλύεται ἄμμα φαρέτρης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`447` Ἀλλʼ ὁ μὲν ἱλήκοι· σὺ δέ μοι, Διὸς, ἔννεπε, Μοῦσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`448` νήσων πασάων ἱερὸν πόρον, αἵτʼ ἐνὶ πόντῳ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`449` ἀνδράσι ναίονται, τετραμμέναι ἄλλυδις ἄλλαι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`450` Ἤτοι μὲν κατὰ μέσσον ὑφεσπερίων στηλάων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`451` ἐσχατόωντα Γάβειρα φαείνεται ἀνθρώποισι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`452` νήσου ἐπ’ ἀμφιρύτης, ἐπὶ τέρμασιν Ὠκεανοῖο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`453` Ἐνθάδε Φοινίκων ἀνδρῶν γένος ἐνναίουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`454` ἁζόμενοι μεγάλοιο Διὸς γόνον Ἡρακλῆα·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`455` καὶ τὴν μὲν ναετῆρες, ἐπὶ προτέρων ἀνθρώπων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`456` κλῃζομένην Κοτινοῦσαν, ἐφημίξαντο Γάδειρα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`457` Νῆσοι δʼ ἑξείης Γυμνήσιαι· ἄγχι δὲ Βοῦσος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`458` Σαρδώ τʼ εὐρυτάτη καὶ ἐπήρατος εἰν ἁλὶ Κύρνος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`459` ἥν ῥά τε Κορσίδα φῶτες ἐπιχθόνιοι καλέουσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`460` ὕλῃ δʼ ἀμφιλαφὴς οὔτις τόσον, ὅσσον ἐκείνη.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`461` Τὴν δὲ μετʼ Αἰόλου εἰσὶ περίδρομοι εἰν ἁλὶ νῆσοι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`462` Αἰόλου Ἱπποτάδαο, φιλοξείνου βασιλῆος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`463` Αἰόλου, ὅς θηητὰ μετʼ ἀνδράσιν ἔλλαχε δῶρα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`464` κοιρανίην ἀνέμων κλονεόντων θʼ ἱσταμένων τε.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`465` Ἑπτὰ δέ οἱ ταί γ εἰσίν,ἐπώνυμοι ἀνδράσι Πλωταί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`466` οὕνεκα μέσσον ἔχουσι περίπλοον ἀμφιέλικτον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`467` Τρινακίη δʼ ἐπὶ τῇσιν ὑπὲρ πέδον Αὐσονιήων ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`468` ἐκτέταται, πλευρῇσιν ἐπὶ τρισὶν ἑστηκυῖα·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`469` ἄκρα δέ οἱ Πάχυνός τε Πελωρίς τε Λιλύβη τε.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`470` Ἀλλʼ ἤτοι Λιλύβη μὲν ἐπὶ ῥιπὴν ζεφύροιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`471` εἰσανέχει, Πάχυνος δὲ πρὸς αὐγάς, αὐτὰρ ἐπʼ ἄρκτους
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`472` ἠνεμόεσσα Πελωρὶς, ἐς Αὐσονίην ὁρόωσα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`473` Τῆς μὲν πρὸς βορέην ὀλοὴ ναύτῃσι κέλευθος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`474` στεινή τε σκολιή τε καὶ ἄσχετος, ἧχι θάλασσα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`475` συρομένη μακρῇσι περιβρέμεται σπιλάδεσσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`476` Ἀονίῳ τμηθεῖσα πολυγλώχινι σιδήρῳ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`477` Πρὸς δὲ νότον Λιβυκός τε πόρος καὶ Σύρτιδος ἀρχὴ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`478` τῆς ἑτέρης· ἑτέρην δʼ ἂν ἴδοις προτέρωσε περήσας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`479` ἑσπερίην· τῆς πρόσθε δύω νησῖδες ἔασι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`480` Μῆνιγξ καὶ Κέρκιννα, Λιβυστικὸν ὅρμον ἔχουσαι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`481` Ἀλλʼ ὁπότ’ Ἀδριάδος σκαιὸν πόρον ἀμφιτρίτης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`482` εἰσελάσῃς ἐπὶ νηός, Ἰηπυγίην ἐπὶ γαῖαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`483` δήεις ἰφθίμου Διομήδεος αὐτίκα νῆσον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`484` ἔνθʼ ἥρως ἀφίκανε, χαλεψαμένης Ἀφροδίτης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`485` ὁππότε τριλλίστων μετεκίαθεν ἔθνος Ἰβήρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`486` ἧς ἀλόχου βουλῇσι κακόφρονος Αἰγιαλείης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`487` Ἑξείης δὲ πόροιο πρὸς αὐγὰς ἠελίοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`488` Ἀψύρτου νήσων ἀναφαίνεται ἄσπετος ὁλκός,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`489` τάς ποτε Κόλχων υἷες ἐπέδραμον, εὖτ’ ἐμόγησαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`490` ἴχνια μαστεύοντες ἀλήμονος Αἰητίνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`491` Ἑξείης δʼ ἐπὶ τῇσι Λιβυρνίδες ἐρρίζωνται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`492` Πρὸς δὲ νότον μετὰ δρυμὰ Κεραύνια νηὶ θεούσῃ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`493` νῆσοί κεν φαίνοιντο περαιόθεν Ἀμπρακιήων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`494` καὶ λιπαρὴ Κέρκυρα, φίλον πέδον Ἀλκινόοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`495` Τῇ δʼ ἔπι Νηρικίης Ἰθάκης ἕδος ἐστήρικται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`496` νήσων τʼ ἀλλάων, ὅσσας τʼ ἀπὸ Χαλκίδος ἕρπων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`497` δίνης ἀργυρέῃς Ἀχελώιος ἀμφὶς ἑλίσσει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`498` Πολλ αὶ δʼ Ἀμνισοὶο βορειότεραι ὁρόωνται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`499` Αἴγιλά τ’ ἠδὲ Κύθηρα Καλαύριά τε τρηχεῖα·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`500` Κάρπαθος αὖθʼ ἑτέρωθι ποτὶ ζόφον· ἐγγύθι δʼ αὐτῆς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`501` Κρήτη τιμήεσσα, Διὸς μεγάλοιο τιθήνη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`502` πολλή τε λιπαρή τε καὶ εὔβοτος, ἧς ὕπερ Ἴδη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`503` Ἴδη, καλλικόμοισιν ὑπὸ δρυσὶ τηλεθόωσα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`504` καὶ τῆς τοι μέγεθος περιώσιον. Ἄντα δὲ πέζης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`505` Αἰγυπτίης Ῥόδος ἐστὶν, Ἰηλυσίων πέδον ἀνδρῶν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`506` Πρόσθε δὲ Σουνιάδος κορυφῆς, ἐφύπερθεν Ἀβάντων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`507` φαίνονται Σαλαμίς τε καὶ Αἰγίνης πτολίεθρον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`508` Κύπρος δʼ εἰς αὐγὰς Παμφυλίου ἔνδοθι κόλπου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`509` κλύζετʼ, ἐπήρατον ἄστυ Διωναίης Ἀφροδίτης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`510` Τὴν δὲ μέτʼ ἀντολίηνδε Χελιδόνιαι γεγάασι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`511` τρεῖς νῆσοι μεγάλης Παταρηΐδος ἔνδοθεν ἄκρης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`512` ἄγχι δὲ Φοινίκης Ἄροδος μεγάλῳ ἐνὶ πόντῳ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`513` Θηητὸς δέ τίς ἐστι βαθὺς πόρος Αἰγαίοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`514` ἐντὸς ἔχων ἑκάτερθεν ἀπειρεσίων στίχα νήσων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`515` ὅσσον ἐπὶ στεινωπὸν ὕδωρ Ἀθαμαντίδος Ἕλλης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`516` Σηστὸς ὅπη καὶ Ἄβυδος ἐναντίον ὅρμον ἔθεντο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`517` Εὐρώπης δʼ αἱ μὲν λαιῆς ὑπὸ νεύματι χειρὸς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`518` ῥώονθʼ ἑξείης, Ἀσίης δʼ ἐπὶ δεξιὰ κεῖνται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`519` μῆκος ἐπ’ ἀρκτῴοιο τιταινόμεναι βορέαο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`520` Εὐρώπης δ ἤτοι μὲν Ἀβαντιὰς ἔπλετο Μάκπις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`521` Σκῦρός τ ἠνεμόεσσα καὶ αἰπεινὴ Πεπάπηθος·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`522` ἔνθεν καὶ Λῆμνος, κρχναὸν πέδον Ἠραίστοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`523` πέπταται, ὠγυγίη τε Θάσος, Δημήτερος ἀκτή,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`524` Ἴμβροζ, Θρηικίη τε Σάμος, Κορυβάντιον ἄστυ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`525` Αἳ δ Ἀσίης πρώτην αἶσαν λάχον, ἀμφίς ἐοῦσαι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`526` Δῆλον ἐκυκλώσαντο, καὶ οὔνομα Κυκλάδες εἶσί·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`527` ῥύσια δʼ Ἀπόλλωνι χοροὺς ἀνάγουσιν ἅπασαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`528` ἱσταμένου γλυκεροῦ νέον εἴαρος, εὖτ’ ἐν ὄρεσσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`529` ἀνθρώπων ἀπάνευθε κυεῖ λιγύφωνος ἀηδών.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`530` Νῆσοι δʼ ἐξείης Σποράδες περιπαμφανόωσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`531` οἷον ὅι’ ἀνεφέλοιο διʼ ἠέρος εἴδεται ἄστρα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`532` ὑγρὰ νέφη κραιπνοῖο βιησαμένου βορέαο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`533` Ταὶς δ ἔπι νῆσοι ἔασιν Ἰωνίδες· ἔνθα δὲ Καῦνος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`534` καὶ Σάμος ἱμερόεσσα, Πελασγίδος ἕδρανον Ἥρης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`535` καὶ Χίος ἠλιβάτοιο Πελινναίου ὑπὸ πέζαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`536` Κεῖθεν δ Αἰολίδων ἀωαφαίνεται οὔρεα νήσων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`537` Λέσβου τ εὐρυχόροτο καὶ ἱμερτῆς Τεωεδοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`538` Κεῖθι Μέλας καὶ κόλπος ἐφʼ Ἑλλήσποντον ἵησιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`539` ἀφρὸν ἐρευγόμενος· βορέην δʼ ἐπὶ πολλὸν ἰόντι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`540` πέπταται ἔνθα καὶ ἔνθα Προποντίδος οἶδμα θαλάσσης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`541` Ἔστι δέ τις καὶ σκαιὸν ὑπὲρ πόρον Εὐξείνοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`542` ἄντα Βορυσθένεος μεγαλώνυμος εἰν ἁλὶ νῆσος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`543` ἡρώων· Λευκήν μιν ἐπωνυμίην καλέουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`544` οὕνεκά οἱ τὰ πάρεστι κινώπετα λευκὰ τέτυκται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`545` κεῖθι δʼ Ἀχιλλῆός τε καὶ ἡρώων φάτις ἄλλων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`546` ψυχὰς εἱλίσσεσθαι ἐρημαίας ἀνὰ βήσσας·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`547` τοῦτο δʼ ἀριστήεσσι Διὸς πάρα δῶρον ὀπηδεῖ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`548` ἀντʼ ἀρετῆς· ἀρετὴ γὰρ ἀκήρατον ἔλλαχε τιμήν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`549` Κιμμέριον δʼ ἄρα τοι διὰ Βόσπορον ἰθὺς ἰόντι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`550` ἄλλη ἀπειρεσίη νῆσος πέλει, ἢ ῥά τε λίμνης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`551` ἔνδοθι δεξιτερῇ Μαιώτιδος ἐστήρικται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`552` ἧς ἔπι Φαιναγόρη τε καὶ εὔκτιτος Ἑρμώνασσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`553` ἔνθα τε ναιετάουσιν Ἰωνίδος ἔκγονοι αἴης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`554` Αἵδε μὲν ἀνθρώποισιν ἀγακλέις εἰν ἁλὶ νῆσοι·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`555` ἄλλαι δʼ Ὠκεανοῖο παρὰ ῥόον ἐστεφάνωνται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`556` τάων δʼ ἂν περίσημον ἐγὼ θέσιν ἐξενέποιμι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`557` ὁπποτέρου τʼ ἀνέμοιο παρὰ σφυρόν ἐστιν ἑκάστη.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`558` Ἤτοι μὲν ναίουσι βοοτρόφον ἄμφʼ Ἐρύθειαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`559` Ἄτλαντος περὶ χεῦμα θεουδέες Αἰθιοπῆες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`560` Μακροβίων υἱῆες ἀμύμονες, οἵ ποθʼ ἵκοντο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`561` Γηρυόνος μετὰ πότμον ἀγήνορος· αὐτὰρ ὑπ ἄκρην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`562` Ἱρὴν, ἣν ἐνέπουσι κάρην ἔμεν Εὐρωπείης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`563` νήσους Ἑσπερίδας, τόθι κασσιτέροιο γενέθλη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`564` ἀφνειοὶ ναίουσιν ἀγαυῶν παῖδες Ἰβήρων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`565` Ἄλλαι δʼ Ὠκεανοῖο παραὶ βορεώτιδας ἀκτὰς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`566` δισσαὶ νῆσοι ἔασι Βρετανίδες, ἀντία Ῥήνου·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`567` κεῖθι γὰρ ὑστατίην ἀπερεύγεται εἰς ἅλα δίνην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`568` Τάων τοι μέγεθος περιώσιον, οὐδέ τις ἄλλη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`569` νήσοις ἐν πάσῃσι Βρετανίσιν ἰσοφαρίζει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`570` Ἄγχι δὲ νησίδων ἕτερος πόρος, ἔνθα γυναῖκες
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`571` ἀνδρῶν ἀντιπέρηθεν ἀγαυῶν Ἀμνιτάων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`572` ὀρνύμεναι τελέουσι κατὰ νόμον ἱερὰ Βάκχῳ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`573` στεψάμεναι κισσοῖο μελαμφύλλοιο κορύμβοις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`574` ἐννύχιαι· παταγῆς δὲ λιγύθροος ὄρνυται ἠχή.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`575` Οὐχ οὕτω Θρήικος ἐπʼ ᾐόσιν Ἀψίνθοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`576` Βιστονίδες καλέουσιν ἐρίβρομον Εἰραφιώτην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`577` οὐδʼ οὕτω σὺν παισὶ μελανδίνην ἀνὰ Γάγγην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`578` Ἰνδοὶ κῶμον ἄγουσιν ἐριβρεμέτῃ Διονύσῳ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`579` ὡς κεῖνον κατὰ χῶρον ἀνευάζουσι γυναῖκες.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`580` Πολλὴν δὲ προτέρωσε ταμὼν ὁδὸν Ὠκεανοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`581` νῆσόν κεν Θούλην εὐεργέϊ νηὶ περήσαις·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`582` ἔνθα μὲν, ἠελίοιο βεβηκότος ἐς πόλον ἄρκτων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`583` ἤμαθ’ ὁμοῦ καὶ νύκτας ἀειφανές ἐκκέχυται πῦρ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`584` λοξοτέρῃ γὰρ τῆμος ἐπιστρέφεται στροφάλιγγι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`585` ἀκτίνων ἰθεῖαν ἐπὶ κλίσιν ἐρχομενάων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`586` μέσφʼ ἐπὶ κυανέους νοτίην ὁδὸν αὖτις ἐλάσσῃ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`587` ἀλλ’ ὁπόταν Σκυθικοῖο βαθὺν ῥόον Ὠκεανοῖο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`588` νηὶ τάμῃς, προτέρω δὲ πρὸς ἠῴην ἅλα κάμψῃς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`589` Χρυσείην τοι νῆσον ἄγει πόρος, ἔνθα καὶ αὐτοῦ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`590` ἀντολίη καθαροῖο φαείνεται ἠελίοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`591` Κεῖθεν δὲ στρεφθεὶς νοτίης προπάροιθε κολώνης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`592` αἶψά κε Κωλιάδος μεγάλην ἐπὶ νῆσον ἵκοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`593` μητέρα Ταπροβάνην Ἀσιηγενέων ἐλεφάντων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`594` ᾗς ὕπερ, οὐρανίῃσιν ἀειρόμενος στροφάδεσσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`595` δινεῖται κατὰ κύκλον ἐν αἰθέρι Καρκίνος αἴθων·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`596` αὐτὴ δʼ εὐρυτάτη μέγεθος πέλει· ἀμφὶ δὲ πάντη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`597` κήτεα θῖνες ἔχουσιν, Ἐρυθραίου βοτὰ πόντου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`598` οὔρεσιν ἠλιβάτοισιν ἐοικότα· τῶν δʼ ὑπὲρ ἄκρων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`599` τέτρηχεν νώτων περιμήκετος ὁλκὸς ἀκάνθης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`600` Δυσμενέων τοι παῖδες, ἑλισσόμενοι περὶ πόντον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`601` κείνοις ἀντήσειαν ἀλώμενοι· οὐ γὰρ ἐρωὴ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`602` λυγροῖς ἐν στομάτεσσιν, ἐπεὶ μέγα χάσμα τέτυκται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`603` πολλάκι δʼ αὖ καὶ νῆα σὺν αὐτοῖς ἀνδράσι νηὸς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`604` κεῖνα καταβρώξειε τεράατα· τοῖς γὰρ ἀλιτροῖς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`605` εἰν ἁλὶ καὶ γαίη κακὰ μυρία θήκατο δαίμων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`606` Ἔστι δέ τοι προτέρω Καρμανίδος ἔκτοθεν ἄκρης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`607` Ὤγυρις, ἔνθα τε τύμβος Ἐρυθραίου βασιλῆος·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`608` ἑκ τῆς δʼ ἂν περάσειας ἐπὶ στόμα Περσίδος ἅλμης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`609` ὁρμηθεὶς βορέηνδε, καὶ Ἴκαρον εἰσαφίκοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`610` Ἴκαρον εἰναλίην, ὅθι Ταυροπόλοιο θεοῖο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`611` βωμοὶ κνισσήεντες ἀδευκέα καπνὸν ἔχουσι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`612` Τόσσας μὲν νήσους ἐπέχει ῥόος Ὠκεανοῖο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`613` εὐρυτέρας· ἕτεραι δέ τʼ ἀπειῤέσιαι γεγάασιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`614` αἱ μὲν ἐπὶ προχοῇσι Λιβυστίδος ἀμφιτρίτης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`615` αἱ δʼ Ἀσίης, αἱ δʼ αὖτε περὶ κλίσιν Εὐρωπείης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`616` Ἄλλαι δʼ ἔλλοθινῆσοι ἀπείριτοι, αἱ μὲν ὑπʼ ἀνδρῶν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`617` ναιόμεναι καὶ νηυσὶν ἐπήρατον ὅρμον ἔχουσαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`618` αἱ δὲ βαθύκρημνοί τε καὶ οὐ ναύτῃσιν ἑτοῖμαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`619` τῶν οὐ ῥηίδιόν μοι ἐνισπέμεν οὔνομα πασέων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`620` Σχῆμα δέ τοι Ἀσίης ῥυσμὸς πέλει ἀμφοτεράων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`621` ἠπείρων, ἑτέρωθεν ἀλίγκιον εἴδεϊ κώνου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`622` ἑλκόμενον κατὰ βαιὸν ἐπʼ ἀντολίης μυχὰ πάσης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`623` ἔνθα τε καὶ στῆλαι Θηβκιγενέος Διονύσου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`624` ἑστᾶσιν, πυμάτοιο παρὰ ῥόον Ὠκεανοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`625` Ἰνδῶν ὑστατίοισιν ἐν οὔρεσιν, ἔνθα τε Γάγγης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`626` λευκὸν ὕδωρ Νυσαῖον ἐπὶ πλαταμῶνα κυλίνδει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`627` Ἀλλʼ οὐκ ἂν τόσσον μέγεθος πέλοι Ἀσίδος αἴης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`628` οὐδʼ ἅπαν εἶδος ἔοικεν ἀλίγκιον· ἐν γὰρ ἐκείναις
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`629` ἠπείροις εἷς πόντος ἔσω ῥόον ἡγεμονεύει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`630` ἐν δʼ Ἀσίη πολὺς Ὠκεανός· τρισσοὺς γὰρ ἑλίσσων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`631` κόλπους κυμαίνοντας ἐρεύγεται, εἰς ἅλα βάλλων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`632` Περσικὸν Ἀράβιόν τε καὶ Ὑρκάνιον βαθυδίνην·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`633` τοὺς δύο μέν νοτίους, τὸν δʼ ἐς βορέην ὁρόωντα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`634` ἐς βορέην ὁρόωντα καὶ ἐς λίβα γείτονα πόντου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`635` Εὐξείνου, τόθι φῶτες ἀπείριτοι ἀμφινέμονται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`636` Μέσσον δʼἀμφοτέρων χθονὸς ἄσπετος ἰσθμὸς ὁρίζει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`637` τῇ καὶ τῇ μακροῖσι τιταινόμενος πεδίοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`638` Μέσσα γε μὴν πάσης Ἀσίης ὄρος ἀμφιβέβηκεν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`639` ἀρξάμενον γαίης Παμφυλίδος ἄχρι καὶ Ἰνδῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`640` ἄλλοτε μὲν λοξόν τε καὶ ἀγκύλον, ἄλλοτε δʼ αὖτε
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`641` ἴχνεσιν ὀρθότατον· Ταῦρον δέ ἑ κικλήσκουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`642` οὕνεκα ταυροφανές τε καὶ ὀξυκάρηνον ὁδεύει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`643` οὔρεσιν ἐκταδίοισι πολυσχιδὲς ἔνθα καὶ ἔνθα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`644` Ἐκ τοῦ ἀπειρέσιοι ποταμοὶ καναχηδὰ ῥέουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`645` οἱ μὲν πρὸς βορέην, οἱ δʼ ἐς νότον, οἱ δʼ ἐπὶ ῥτπὴν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`646` εὔρου καὶ ζεφύροιο· τίς ἂν πάντʼ οὐνόματʼ εἴποι;
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`647` Οὐ μὲν ἐπωνυμίην μίαν ἔλλαχεν, ἀλλ ἐν ἑκάστῃ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`648` οὔνομ ἔχει στποφάλιγγι· τὰ δ ἂν κείνοισι μέλοιτο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`649` ἀνδράσιν, οἳ κατὰ χῶρον ὁμούριον οἶκον ἔθεντο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`650` Νῦν γε μὲν ἔθνεα πάντα διίξομαι, ὅσσ’ ἀρίδηλα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`651` ἐνναίει Μοῦσαι δʼ ἰθύντατον ἴχνος ἄγοιεν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`652` Ἤτοι μὲν λίμνης Μαιώτιδος ἄγχι νέμονται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`653` αὐτοὶ Μαιῶταί τε καὶ ἔθνεα Σαυροματάων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`654` ἐσθλὸν ἐνυαλίου γένος Ἄρεος· ἐκ γὰρ ἐκείνης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`655` ἰφθίμης φιλότητος Ἀμαδονίδων ἐγένοντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`656` τήν ποτε Σαυρομάτῃσιν ἐπʼ ἀνθρώποισι μίγησαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`657` πλαγχθεῖσαι πάτρηθεν ἀπόπροθι Θερμώδοντος.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`658` Τοὔνεκα καὶ παῖδες μεγαλήτορες ἐξεγένοντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`659` ὕλην ναιετάοντες ἀπείριτον, ἧς διὰ μέσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`660` συρόμενος Τάναϊς Μαιώτιδος ἐς μυχὰ πίπτει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`661` ὅστε καὶ Εὐρώπην ἀποτέμνεται Ἀσίδος αἴης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`662` ἐς δύσιν Εὐρώπην, ἐς δʼ αὐγὰς Ἀσίδα γαῖαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`663` Τοῦ δʼ ἤτοι πηγαὶ μὲν ἐν οὔρεσι Καυκασίοισι45
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`664` τηλόθι μορμύρουσιν· ὁ δὲ πλατὺς ἔνθα καὶ ἔνθα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`665` ἐσσυμένος Σκυθικοῖσιν ἐπιτροχάει πεδίοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`666` Τοῦ δʼ ἂν, κυμαίνοντος ἀπείριτον ἐκ βορέαο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`667` πηγετὸν ἀθρήσειας ἀπὸ κρυμοῖο παγέντα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`668` Σχέτλιοι, οἳ περὶ κεῖνον ἐνοίκια χῶρον ἔχουσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`669` αἰεί σφιν ψυχρή τε χιὼν κρυμός τε δυσαής·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`670` καὶ δέ κεν, ἐξ ἀνέμων ὁπόταν πλεῖστονκρύος ἔλθῃ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`671` ἢ ἵππους θνήσκοντας ἐν ὀφθαλμοῖσιν ἶδοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`672` ἠὲ καὶ ἡμιόνους ἢ ἀγραύλων γένος οἰῶν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`673` οὐδὲ μὲν οὐδʼ αὐτοί κεν ἀπήμαντοι τελέθοιεν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`674` ἀνέρες, οἳ κείνχσιν ὑπαὶ ῥιπῆσι μένοιεν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`675` ἀλλὰ γὰρ ἠλάσκουσιν, ὑποζεύξαντες ἀπήνας
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`676` χώρην εἰς ἑτέρην, λείπουσι δὲ γαῖαν ἀήταις
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`677` χειμερίοις, οἵτε σφι κακῇ θύοντες ἀέλλῃ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`678` γαῖάν τε κλονέουσι καὶ οὔρεα πευκήεντα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`679` Τόσσοι μὲν Τάναϊν ποταμὸν περιναιετάουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`680` Σαυρομάτας δʼ ἐπέχουσιν ἐπασσύτεροι γεγαῶτες
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`681` Σινδοὶ, Κιμμέριοί τε καὶ οἱ πέλας Εὐξείνοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`682` Κερκέτιοι Τορέται τε καὶ ἀλκήεντες Ἀχαιοί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`683` τούς ποτʼ ἀπὸ Ξάνθοιο καὶ Ἰδαίου Σιμόεντος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`684` πνοιαὶ νοσφίσσαντο νότοιό τε καὶ ζεφύροιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`685` ἑσπομένους μετὰ δῆριν Ἀρητιάδῃ βασιλῆι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`686` Τοῖς δʼ ἔπι ναιεταουσιν, ὁμούριον αἶαν ἔχοντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`687` Ἡνίοχοι Ζύγιοί τε, Πελασγίδος ἔκγονοι αἴης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`688` Πὰρ δὲ μυχὸν Πόντοιο, μετὰ χθόνα Τυνδαριδάων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`689` Κόλχοι ναιετάουσι, μετήλυδες Αἰγύπτοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`690` Καυκάσου ἐγγὺς ἐόντες, ὃς Ὑρκάνιον περὶ πόντον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`691` οὔρεσιν ἠλιβάτοισιν ἀέξεται ἔνθα τε Φᾶσις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`692` Κιρκαίου κατὰ νῶτον ἑλισσόμενος πεδίοιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`693` Εὐξείνου ποτὶ χεῦμα θοὴν ἀπερεύγεται ἄχνην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`694` ἀρξάμενος τὸ πρῶτον ἀπʼ οὔρεος Ἀρμενίοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`695` Τοῦ δὲ πρὸς ἀντολίην βορέην τ ἐπικέκλιται ἰσθμός,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`696` ἰσθμὸς Κασπίης τε καὶ Εὐξείνοιο θαλάσσης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`697` Τῷ δʼ ἔπι ναιετάουσιν ἑωθινὸν ἔθνος Ἰβήρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`698` οἳ ποτε Πυρήνηθεν ἐπʼ ἀντολίην ἀφίκοντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`699` ἀνδράσιν Ὑρκανίοισιν ἀπεχθέα δῆριν ἔχοντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`700` καὶ Καμαριτάων φῦλον μέγα, τοι ποτε Βάκχον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`701` Ἰνδῶν ἐκ πολέμοιο δεδεγμένοι ἐξείνισσαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`702` καὶ μετὰ Ληνάων ἱερὸν χορὸν ἐστήσαντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`703` ζώματα καὶ νεβρῖδας ἐπὶ στήθεσσι βαλόντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`704` εὐοῖ Βάκχε λέγοντες· ὁ δὲ φρεσὶ φίλατο δαίμων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`705` κείνων ἀνθρώπων γενεὴν καὶ ἤθεα γαίης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`706` Τοῖς δʼ ἔπι Κασπίη κυμαίνεται ἀμφιτρέτη.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`707` Ῥεῖα δέ τοι καὶ τήνδε καταγράψαιμι θάλασσαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`708` οὐ μὲν ἰδὼν ἀπάνευθε πόρους, οὐ νηὶ περήσας·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`709` οὐ γάρ μοι βίος ἐστὶ μελαινάων ἐπὶ νηῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`710` οὐδέ μοι ἐμπορίη πατρώιος, οὐδʼ ἐπὶ Γάγγην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`711` ἔρχομαι, οἷά τε πολλοὶ, Ἐρυθραίου διὰ κόντου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`712` ψυχῆς οὐκ ἀλέγοντες, ἵνʼ ἄσπετον ὄλβον ἕλωνται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`713` οὐδὲ μὲν Ὑρκανίοις ἐπιμίσγομαι, οὐδʼ ἐρεείνω
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`714` Καυκασίας κνημῖδας Ἐρυθραίων Ἀριηνῶν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`715` ἀλλά με Μουσάων φορέει νόος, αἵτε δύνανται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`716` νόσφιν ἀλημοσύνης πολλὴν ἅλκ μετρήσασθαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`717` οὔρεά τʼ ἤπειρόν τε καὶ αἰθερίην ὁδὸν ἄστρων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`718` Ἀλλʼ εἴη τοι σχῆμα περίδρομον, ἀμφιέλικτον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`719` πάσης Κασπίης μεγάλης ἁλός· οὐκ ἂν ἐκείνην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`720` νηὶ περήσειας τριτάτης ἐπὶ κύκλα σελήνης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`721` τόσσος γὰρ πόρος ἐστὶν ἀμείλιος· ἂψ δὲ μετ ἄρκτους
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`722` ἐλκόμενος, προχοῆς ἐπιμίσγεται Ὠκεανοῖο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`723` ἣ δὴ πολλὰ μὲν ἄλλα μετʼ ἀνδράσι θαύματʼ ἀέξει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`724` φύει δὲ κρύσταλλον ἰδʼ ἠερόεσσαν ἴασπιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`725` ἐχθρὴν ἐμπούσησι καὶ ἄλλοις εἰδώλοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`726` Πάντα δέ τοι ἐρέω, ὅσα μιν πέρι φῦλα νέμονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`727` ἀρξάμενος πλευρῆς ζεφυρίτιδος ἐκ βορέαο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`728` Πρῶτοι μὲν Σκύθαι εἰσὶν, ὅσοι Κρονίης ἁλὸς ἄγχι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`729` παραλίην ναίουσιν ἀνὰ στόμα Κασπίδος ἅλμης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`730` Οὖννοι δʼ ἐξείης· ἐπὶ δʼ αὐτοῖς Κάσπιοι ἄνδρες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`731` Ἀλβανοί τʼ ἐπὶ τοῖσιν ἀρήιοι, οἵ θʼ ὑπέρ αἶαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`732` τρηχεῖαν ναίουσι Καδούσιοι ἄγχι δὲ Μάρδοι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`733` Ὑρκάνιοι Τάπυροί τ · ἐκὶ δέ σφισιν ὁλκὸν ἑλίσσει
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`734` Μάρδος, Δερκεβίων τε καὶ ἀφνειῶν πόμα Βάκτρων·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`735` ἀμφοτέρων γὰρ μέσσος ἐς Ὑρκανίην ἅλα βάλλει·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`736` ἀλλʼ ἤτοι Βάκτροι μὲν ἐπ’ ἡπείροιο νέμονται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`737` χώρην εὐρυτέρην κνημοῖς ὑπὸ Παρνησοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`738` Δερκέβιοι δ ἑτέρωθεν ἐφ ὕδασι Κασπίοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`739` Τοὺς μέτ ἀντολίηνδε, πέρην κελάδοντος Ἀράξεω
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`740` Μασσαγέται ναίουσι, θοῶν ῥυτῆρες ὀῖστῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`741` ἀνέρες, οἷς μήτʼ αὐτὸς ἐγὼ, μήθʼ ὅστις ἑταῖρος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`742` ἐμπελάσαι· μάλα γάρ τε κακοξεινώτεροι ἄλλων·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`743` οὐ γάρ σφιν σίτοιο μελίφρονός ἐστιν ἐδωδή,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`744` οὐδὲ μὲν οὐδʼ οἶνος μεταδήμιος· ἀλλὰ γὰρ ἵππων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`745` αἵματι μίσγοντες λευκὸν γάλα, δαῖτα τίθενται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`746` Τοῖς δʼ ἔπι πρὸς βορέην Χωράσμιοι, οἶς ἔπι γαῖα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`747` Σουγδιάς, ἧς ἀνὰ μέσσον ἑλίσσεται ἱερὸς Ὦξος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`748` ὅστε λιπὼν Ἠμωδὸν ὄρας μετὰ Κασπίδα βάλλει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`749` Τὸν μέτʼ ἐπὶ προχοῇσιν Ἰαξάρταο νέμονται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`750` τόξα Σάκαι φορέοντες, ἃ μή κέ τις ἄλλος ἐλέγχοι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`751` τοξευτής οὐ γάρ σφι θέμις ἀνεμώλια βάλλειν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`752` καὶ Τόχαροι Φροῦνοί τε καὶ ἔθνεα βάρβαρα Σηρῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`753` οἵτε βόας μὲν ἀναίνονται καὶ ἴφια μῆλα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`754` αἰόλα δὲ ξαίνοντες ἐρήμης ἄνθεα γαίης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`755` εἳματα τευχουσιν πολυδαίδαλα, τιμήεντα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`756` εἰδόμενα χροιῇ λειμωνίδος ἄνθεσι ποίης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`757` κείνοις οὔ τί κεν ἔργον ἀραχνάων ἐρίσειεν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`758` Ἄλλοι δὲ Σκύθαι εἰσὶν ἐπήτριμοι, οἵτε νέμονται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`759` ἐσχατιάς· παρὰ δέ σφι δυσήνεμος ἐκτέταταιχθών,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`760` χειμερίοις ἀνέμοισι λελειμμένη ἠδὲ χαλάζαις.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`761` Τόσσοι μὲν φῶτες περὶ Κάσπια κύματʼ ἔασιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`762` φράζεο δʼ ἐκ Κόλχων καὶ Φάσιδος ἐς δύσιν ἤδη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`763` Εὐξείνου παρὰ χεῖλος, ἐπιλαδὸν ἔθνεα Πόντου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`764` ἄχρι Θρηικίου στόματος, τόθι Χαλκὶς ἄρουρα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`765` Βύζηρές τοι πρῶτα καὶ ἀγχόθι φῦλα Βεχείρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`766` Μάκρωνες Φίλυρές τε καὶ οἳ μόσσυνας ἔχουσι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`767` δουρατέους· τῶν δʼ ἄγχι πολύρρηνες Τιβαρηνοί·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`768` τοῖς δ ἔπι καὶ Χάλυβεςστυρελὴν καὶ ἀπήνεα γαῖαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`769` ναίουσιν, μογεροῦ δεδκηκότες ἔργα σιδήρου,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`770` οἵ ῤα, βαρυγδούποισιν ἐπʼ ἄκμοσιν ἑστηῶτες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`771` οὔποτε παύονται καμάτου καὶ ὀϊζύος αἰνῆς.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`772` Τοὺς δὲ μέτʼ Ἀσσυρίης πρόχυσις χθονὸς ἐκτετάνυσται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`773` ἔνθα δʼ Ἀμαζονίδεσσιν ἀπʼ οὔρεος Ἀρμενίοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`774` λευκὸν ὕδωρ προΐησιν ἐνυάλιος Θερμώδων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`775` ὅς ποτʼ ἀλωομένην Ἀσωπίδα δέκτο Σινώπην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`776` καί μιν ἀκηχεμένην σφετέρῃ παρενάσσατο χώρῃ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`777` Ζηνὸς ἐφημοσύνῃσιν· ὁ γὰρ φιλότητος ἐρκννῆς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`778` ἰσχανόων, πάτρης ἀπενόσφισεν οὐκ ἐθέλουσαν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`779` ἐκ τῆς καὶ πτολίεθρον ἐπώνυμον ἄνδρες ἔχουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`780` Κείνου δʼ ἂν ποταμοῖο περὶ κρυμώδεας ὄχθας
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`781` τέμνοις κρυστάλλου καθαρὸν λίθον, οἷά τε πάχνην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`782` χειμερίην· δήεις δὲ καὶ ὑδατόεσσκν ἴασπιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`783` Ἶρις δʼ ἑξείης καθαρὸν ῥόον εἰς ἅλα βάλλει.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`784` Τῷ δʼ ἔπι μορμύρουσι ῥοαὶ Ἅλυος ποταμοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`785` ἑλκόμεναι βορέηνδε Καραμβίδος ἐγγύθεν ἄκρης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`786` ἀρξάμεναι τὸ πρῶτον ἀπʼ οὔρεος Ἀρμενίοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`787` Παφλαγόνες δʼ ἐπὶ τοῖσιν ἐπ’ ἠιόνεσσι νέμονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`788` καὶ Μαριανδυνῶν ἱερὸν πέδον· ἔνθʼ ἐνέπουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`789` οὐδαίου Κρονίδαο μέγαν κύνα χαλκεόφωνον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`790` χερσὶν ἀνελκόμενον μεγαλόφρονος Ἡρακλῆος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`791` δεινὸν ἀπὸ στομάτων βαλέειν σιαλώδεα χυλόν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`792` τὸν μέν ἐδέξατο γαῖα καὶ ἀνδράσι πῆμʼ ἐφύτευσεν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`793` Ἄγχι δὲ Βιθυνοὶ λιπαρήν χθόνα ναιετάουσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`794` Ῥήβας ἔνθʼ ἐρατεινὸν ἐπιπροΐησι ῥέεθρον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`795` Ῥήβας, ὃς Πόντοιο παρὰ στομάτεσσιν ὁδεύει,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`796` Ῥήβας, οὗ κάλλιστον ἐπὶ χθονὶ σύρεται ὕδωρ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`797` Τόσσοι μὲν Πόντοιο περικτίται ἄνδρες ἔασι·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`798` κεῖνα δέ τοι Σκυθίης προλελεγμένα φῦλα πελέσθω.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`799` Νῦν δʼ αὖ παραλίης Ἀσίης πόρον ἐξενέποιμι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`800` ὅς ῥά τε πρὸς νότον εἰσιν ἐφʼ Ἑλλήσποντον ὁδεύων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`801` καὶ ποτὶ μηκίστου νότιον ῥόον Αἰγαίοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`802` μέσφʼ αὐτῆς Συρίης τε καὶ Ἀραβίης ἐρατεινῆς.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`803` Χαλκιδέες μὲν πρῶτα παρὰ στόμα γαῖαν ἔχουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`804` οὖδας ἐς ἀντιπέρην βυζάντιον εἰσορόωντες·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`805` Βέβρυκες δʼ ἐπὶ τοῖσι καὶ οὔρεα Μυσίδας αἴης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`806` ᾗχί περ ἱμερόεντα Κίος προΐησι ῥέεθρα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`807` τοῦ ποτʼ ἐπὶ προχοῇσιν Ὕλαν ἡρπάξατο Νύμφη, κὼν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`808` ὀτρηρὸν θεράποντα πελωρίου Ἡρακλῆος.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`809` Ἔνθεν ἐφʼ Ἑλλήσποντον ἐπιτρέχει ἄσπετος ἀγβαιοτέρης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`810` Φρυγίης· ἑτέρη δέ τοι ἔνδοθι κεῖται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`811` εὐρυτέρη γεγαυῖα, παρʼ ὕδασι Σαγγαρίοιο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`812` ἀλλʼ ἤτοι μεγάλη μὲν ἐπʼ ἀντολίην τετάνυσται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`813` ἱππόβοτος, λιπαρή τε· πρὸς ἑσπερίην δ ἂν ἴδκο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`814` τὴν ἑτέρην, ἣ κεῖται ὑπὸ ζαθέης κόδας Ἴδης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`815` Ἴλιον, ἠνεμόεσσαν ὑπὸ πλευρῇσιν ἔχουσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`816` Ἴλιον ἀγλαὸν ἄστυ παλαιγενέων ἡρώων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`817` Ἴλιον, ἣν ἐπόλισσε Ποσειδάων καὶ Ἀπόλλων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`818` Ἵλιον, ἣν ἀλάπαξαν Ἀθηναίη τε καὶ Ἥρη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`819` Ξένθῳ ἔπʼ εὐρυρέοντι καὶ Ἰδαίῳ Σιμόεντι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`820` Τὴν δὲ μέτʼ Αἰολίδος παραπέπταται ἔθεα γαίης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`821` Αἰγαίου παρὰ χεῖλος, ὑπέρ μέγαν Ἑλλήσποντον.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`822` Τῇ δʼ ἔπι ναιετάουσιν ἀγαυῶν ἔθνος Ἰώνων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`823` ἀγχίαλοι γεγαῶτες, ἐπὶ χθονὸς, ἧς διὰ μέσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`824` Μαίανδρος λιπαρῇσι κατέρχεται εἰς ἅλα δίναις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`825` Μιλήτου τε μεσηγὺ καὶ εὐρυχόροιο Πριήνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`826` Τάων ἀμφοτέρων γε βορειοτέρην ἐσίδοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`827` παραλίην Ἔφεσον, μεγάλην πόλιν Ἰοχεαίρης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`828` ἔνθα θεῇ ποτε νηὸν Ἀμαζονίδες τετύκοντο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`829` πρέμνῳ ἔνι πτελέης, περιώσιον ἀνδράσι θαῦμα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`830` Μῃονίη δʼ ἐπὶ τοῖσιν ἐπ ἀντολίην τετάνυσται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`831` Τμώλῳ ὔπ’ ἠνεμόεντι, τόθεν Πακτωλὸς ὁδεύων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`832` χρυσὸν ὁμοῦ δίνησιν ἐφελκόμενος κελαρύζει
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`833` τοῦ δʼ ἂν ἐπὶ πλευρῇσι καθήμενος εἴαρος ὥρῃ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`834` κύκνων εἰσαΐοις λιγυρὴν ὄπα, τοί τε καθʼ ὕδωρ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`835` ἔνθα καὶ ἔνθα νέμονται ἀεξομένης ἐπὶ ποίης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`836` πολλοὶ γὰρ λειμῶνες ἐν Ἀσίδι τηλεθόωσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`837` ἔξοχα δʼ ἀμπεδίον Μαιάνδριον, ἔνθα Καΰστρου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`838` ἥσυχα καχλάζοντος ἐπιρρέει ἀγλαὸν ὕδωρ.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`839` Οὐ μὰν οὐδὲ γυναῖκας ὀνόσσεαι, αἳ περὶ κεῖνο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`840` θεῖον ἕδος, χρυσοῖο κατʼ ἰξύος ἔμμα βαλοῦσαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`841` ὀρχεῦνται, θηητὸν ἑλισσόμεναι περὶ κύκλον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`842` εὖτε Διωνύσοιο χοροστασίας τελέοιεν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`843` σὺν καὶ παρθενικαὶ νεοθηλέες, οἷά τε νεβροί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`844` σκαίρουσιν· τῇσιν δὲ περισμαραγεῦντες ἀῆται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`845` ἱμερτοὺς δονέουσιν ἐπὶ στήθεσσι χιτῶνας.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`846` Ἀλλὰ τὰ μὲν Λυδοῖσι μετʼ ἀνθρώποισι μέλονται
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`847` πρὸς δʼ ἅλα κεκλιμένοι Λύκιοι χθόνα ναιετάουσι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`848` Ξάνθου ἐπὶ προχοῇσιν, ἐϋρρείτου ποταμοῖο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`849` ἔνθα βαθυκρήμνοιο φαείνεται οὔρεα Ταύρου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`850` Παμφύλων καὶ μέχρι· Κράγον δέ ἑ φημίζουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`851` Κεῖθι δʼ ἂν ἀθρήσειας ὑπειράλιον πτολίεθρον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`852` Ἄσπενδον, ποταμοῖο παρὰ ῥόον Εὐρυμέδοντος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`853` ἔνθα συοκτονίῃσι Διωναίην ἱλάονται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`854` Ἄλλαι δʼ ἑξείης Παμφυλίδες εἰσὶ πόληες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`855` Κώρυκος Πέργη τε καὶ ἤνεμόεσσα Φάσηλις.57
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`856` Τῶν δὲ πρὸς ἀντολιην μεσάτην χθόνα ναιετάουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`857` ἴδριες ἐν πολέμοισι Λυκάονες ἀγκυλότοξοι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`858` Τοῖς δʼ ἔπι Πισιδέων λιπαρὸν πέδον, ἧχι πόληες γη.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`859` Τερμησσὸς Λύρβη τε καὶ ἣν ἐπολίσσατο λαὸς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`860` πρίν ποτʼ Ἀμυκλαίων μεγαλώνυμος ἐν χθονὶ Σέλ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`861` Κεῖθεν δʼ εἶς αὐγὰς σκολιὸν περιτέμνεται οἶμον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`862` πολλὸν ἔσω βεβαυῖα περίδρομος ἀμφιτρίτη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`863` γείτων Εὐξείνοιο πολυκλύστοιο θαλάσσης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`864` Κεῖνός τοι Κιλίκων περισύρεται ἔθνεα κόλπος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`865` μακρὸς ἐπʼ ἀντολίην· Ἀσίης δὲ στεινὰ καλεῦσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`866` Καὶ τῶ μὲν πλεόνων ποταμῶν ἐπιμίσγεται ὕδωρ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`867` τηλόθεν ἐρχομένων, Πυράμοιότε καὶ Πινάροιο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`868` Κύδνου τε σκολιοῖο, μέσην διὰ Ταρσὸν ἰόντος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`869` Ταρσὸν ἐϋκτιμένην, ὅθι δή ποτε Πήγασος ἵππος,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`870` ταρσὸν ἀφεὶς, χώρῳ λίπεν οὔνομκ, τῆμος ἀφ ἵππου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`871` ἐς Διὸς ἱέμενος πέσεν ἥρως Βςλλεροφόντης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`872` Κεῖθι δὲ καὶ πεδίον τὸ Ἀλήιον, οὗ κατὰ νῶτα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`873` ἀνθρώπων ἀπάνευθεν ἀλώμενος ἐνδιάασκεν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`874` Πολλαὶ δ ἑξείης Κιλίκων γεγάκσι πόληες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`875` Λυρνησσὸς Μαλλός τε καὶ Ἀγχιάλεια Σόλοι τε,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`876` αἱ μὲν ἐν ἠπείρῳ, αἱ δʼ αὐτῆς ἄγχι θαλάσσης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`877` Τῇς δʼ ἔπι Κομμαγεηνὸν ἕδος, Συρίης τε πόληες
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`878` θινὸς ἐπὶ στρεπτῆς περιμήκεες· ἀμφὶ γὰρ ὁλκὸς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`879` ἐς δύσιν ἔστραπται πολιῆς ἁλὸς, ἄχρι κολώνης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`880` οὔρεος ἀγχιάλοιο, βαθυκρήμνου Κασίοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`881` Ῥηιδίως δʼ ἄν τοι λοιπὸν πόρον αὐδήσαιμι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`882` γαιάων Ἀσίης· ὁ δέ τοι λόγος ἐν φρεσὶν ἔστω,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`883` μηδʼ ἀνέμοις φορέοιτο πονηθέντων χάρις ἔργων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`884` Εἰ γάρ μοι σάφα τήνδε καταφράσσαιο κέλευθον,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`885` ἦ τάχα κἂν ἄλλοισιν ἐπισταμένως ἀγορεύοις
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`886` καὶ ποταμοὺς,πολίων τε θέσιν καὶ γαῖαν ἑκάστην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`887` Σχῆμα μὲν οὖν πισύρεσσιν ἐπὶ πλευρῇσι τετύχθω,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`888` πεπταμένον δολιχοῖσιν ἐπʼ ἀντολίην πεδίοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`889` Οἶσθα μὲν, ἐν πρώτοισιν ἐμεῦ εἰπόντος ἀκούσας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`890` πᾶσαν ἕως Ἰνδῶν Ἀσίην ὄρος ἄνδυχα τέμνειν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`891` Κεῖνό τοι ἐν πλευρῇσι βορειότερον τελέοιτο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`892` Νεῖλος δʼ ἑσπέριον πλευρὸν πέλοι· αὐτὰρ ἑῷον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`893` Ἰνδικὸς Ὠκεανός·νότιον δ ἁλὸς οἴδματ’ Ἐρυθρῆς.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`894` Φράζεο δʼ ὡς ὑπὸ πέζαν ἐπʼ αὐγὰς ἵξομαι ἤδη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`895` ἀρξάμενος Συρίηθεν, ὅθεν λίπον· οὐδʼ ἂν ἔμοιγε
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`896` μύθου ἄτε ψευσθέντος ἀνὴρ ἐπιμωμήσαιτο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`897` Ἀλλʼ ἤτοι Συρίη μὲν ὑπεὶρ ἁλὸς ἐγγύθεν ἕρπει
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`898` ἐς νότον ἀντολίην τε, πολύπτολιν αἶαν ἔχουσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`899` ἣν Κοίλην καλέουσιν ἐπώνυμον, οὕνεκ’ ἄρʼ αὐτὴν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`900` μέσσην καὶ χθαμαλὴν ὀρέων ὑπὸ πρῶνες ἔχουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`901` ἑσπερίου Κασίοιο καὶ ἠῴου Λιβάνοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`902` Καὶ τὴν μὲν πολλοί τε καὶ ὄλβιοι ἄνδρες ἔχουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`903` οὐχ ἅμα ναιετάοντες ὁμώνυμοι, ἀλλὰ διαμφίς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`904` οἱ μὲν ἐπʼ ἠπείρῳ, τοίπερ Σύριοι καλέονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`905` οἱ δʼ ἁλὸς ἐγγὺς ἐόντες, ἐπωγυμίην Φοίνικες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`906` τῶν ἀνδρῶν γενεῆς, οἳ Ἐρυθραῖοι γεγάασιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`907` οἳ πρῶτοι νήεσσιν ἐπειρήσαντο θαλάσσης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`908` πρῶτοι δʼ ἐμπορίης ἁλιδινέος ἐμνήσαντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`909` καὶ βαθὺν οὐρανίων ἄστρων πόρον ἐφράσσαντο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`910` οἵτ’ Ἰόπην καὶ Γάζαν Ἐλαίδα τʼ ἐνναίουσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`911` καὶ Τύρον ὠγυγίην, Βηρυτοῦ τʼ αἶαν ἐραννήν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`912` Εύβλον τʼ ἀγχίαλον καὶ Σιδῶνʼ ἀνθεμόεσσαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`913` ναιομένην χαρίεντος ἐφʼ ὕδασι Βοστρηνοῖο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`914` καὶ Τρίπολιν λιπαρὴν, Ὀρθωσίδα τε Μάραθόν τε
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`915` Λαοδίκην θ, ἣ κεῖται ἐπʼ ἠιόνεσσι θαλάσσης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`916` καὶ Ποσιδήια ἔργα καὶ ἱερὰ τέμπεα Δάφνης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`917` [ᾗχί περ Ἀντιόχοιο ἐπώνυμος Ἀντιόχεια.?]
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`918` Αὐτὰρ ἐνὶ μέσσῃσιν Ἀπαμείης πτολίεθρον·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`919` τῆς δὲ πρὸς ἀντολίην κατασύρεται ὑγρὸς Ὀρόντης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`920` ἄσπετος, Ἀντιόχοιο μέσην διὰ γαῖαν ὁρίζων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`921` Πᾶσα δέ τοι λιπαρή τε καὶ εὔβοτος ἔπλετο χώρη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`922` μῆλά τε φερβέμεναι καὶ δένδρεσι καρπὸν ἀέξειν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`923` Τῆς δʼ ἂν ἴδοις προτέρω, νοτιώτερον οἶμον ὁδεύων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`924` Ἀραβίου κόλπου μύχατον πόρον, ὅστε μεσηγὺ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`925` εἱλεῖται Συρίης τε καὶ Ἀραβίης ἐρατεινῆς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`926` τυτθὸν ἐπ ἀντολίην τετραμμένος, ἄχρις Ἐλάνων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`927` Κεῖθεν δʼ ὀλβίστων Ἀράβων παρακέκλιται αἶα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`928` πολλὸν ἀνερχομένη, δισσῇ ζωσθεῖσα θαλάσσῃ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`929` Περσίδι τʼ Ἀραβίῃτʼ ·ἄνεμον δέ τοι ἔλλαχ ἑκάστη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`930` Ἀραβίη ζέφυρον, Περσὶς δʼ εὔροιο κελεύθους.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`931` Πίζα δέ τοι νοτίη, τετραμμένη ἀντολίηνδε,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`932` κλύζετʼ Ἐρυθραίοις ὕπο κύμασιν Ὠκεανοῖο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`933` Καὶ τῆς τοι θέσιας μυθήσομαι· ἔξοχα γάρ μιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`934` πασάων πολύολβα καὶ ἀγλαὰ φῦλα νέμονται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`935` Ἄλλο δέ τοι καὶ θαῦμα μέγ ἔξοχον ἔλλαχ ἐκείνη·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`936` αἰεὶ κηώεσσα θύοις ὕπο λαρὸν ὄδωδεν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`937` ἢ θύου ἢ σμύρνης εὐώδεος ἢ καλάμοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`938` ἢ καὶ θεσπεσίοιο πεπαινομένου λιβάνοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`939` ἢ κασίης· ἐτεὸν γὰρ ἀνὰ χθόνα λύσατο κείνην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`940` Ζεὺς αὐτὸς Διόνυσον ἐϋρραφέος παρὰ μηροῦ·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`941` τῷ καὶ γεινομένῳ κηώδεα φύετο πάντα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`942` Μῆλα δὲ καὶ τῆμος λασίοις ἐβαρύνετο μαλλοῖς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`943` ἐν νομῷ, αὐτόματοι δέ κατέρρεον ὕδασι λίμναι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`944` ὄρνιθες δʼ ἑτέρωθεν ἀοικήτων ἀπὸ νήσων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`945` ἦλθον φύλλα φέροντες ἀκηρασίων κιναμώμων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`946` Αὐτὰρ ὁ νεβρίδας μὲν ἐπωμαδίας ἐτάνυσσε,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`947` κισσῷ δʼ ἱμερόεντι καλὰς ἔστεψεν ἐθείρας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`948` ἀκροχάλιξ δʼ οἴνῳ πλεκτοὺς ἀνεσείσατο θύρσους,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`949` μειδιόων, καὶ πολλὸν ἐπ’ ἀνδράσιν ὄλβον ἔχευεν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`950` Τοὔνεκεν εἰσέτι νῦν λιβάνῳ κομόωσιν ἄρουραι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`951` οὔρεα δὲ χρυσῷ, ποταμοὶ δʼ ἑτέρωθι θυηλαῖς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`952` αὐτοὶ δʼ ἐνναέται μάλα πίονα δῆμον ἔχουσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`953` χροσείοις πέπλοισιν ἀγαλλόμενοι μαλακοῖσιν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`954` ἀλλʼ ἤτοι πρῶτοι μὲν ὑπὲρ κλιτὺν Λιβάνοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`955` ἀφνειοὶ ναίουσιν ἐπωνυμίην Ναβαταῖοι·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`956` ἄγχι δὲ Χαυλάσιοί τε καὶ Ἀγρέες, οἷς ἔπι γαῖα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`957` Χατραμὶς ἐνναίει κατεναντία Περσίδος αἴης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`958` Αὐτὰρ Ἐρθθρκάης πλευρὸν ναίουσι θαλάσσης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`959` Μινναῖοί τε Σάβαι τε καὶ ἀγχίγυοι Κλεταβηνοί.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`960` Τόσσα μὲν Ἀραβίην περιώσια φῦλα νέμονται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`961` ἄλλα δέ τοι καὶ πλεῖστα περι πρὸ γάρ ἐστιμεγίστη.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`962` Τῆς δὲ πρὸς ἀντιπέραιαν ὑπαὶ ῥιπὴν ζεφύροιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`963` λυπρὸν ὀρεσκῴων παραφαίνεται οὖδας Ἐρεμβῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`964` οἳ βίον ἐν πέτρῃσι κατωρυχέεσσιν ἔθεντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`965` γυμνοὶ καὶ κτεάνων ἐπιδευέες· ἀμφὶ δʼ ἄρα σφιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`966` ἴδεϊ θαλπομένοισι μελαίνεται αὐαλέος χρώς·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`967` αὔτως δ, οἱά τε θῆρες, ἀλώμενοι ἄλγεʼ ἔχουσιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`968` οὐχ ὡς ἁβροβίων Ἀράβων γένος· οὐ γὰρ ἐν ὄλβῳ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`969` ἴσην μοῖραν ἅπασιν ἐπ’ ἀνδράσι θήκατο δαίμων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`970` Αὐτὰρ ὑπὲρ Λιβάνοιο πρὸς αὐγὰς ἠελίοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`971` ης Συρίης δολιχὴ μηκύνεται αἶα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`972` ἑλκομένη καὶ μέχρις ἁλικλύστοιο Σινώπης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`973` τῆς δʼ ἤτοι μέσσης μὲν ἐπʼ ἠπείροιο βαθείης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`974` Καππαδόκαι ναίουσι, δαήμονες ἱπποσυνάων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`975` Ἀσσύριοι δʼ ἁλὸς ἄγχι παρὰ στόμα Θερμώδοντος.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`976` Τῆς δὲ πρὸς ἀντολίην ὀρέων ἀπὸ παιπαλοέντων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`977` φαίνετʼ ἀπειρεσίου ποταμοῦ ῥόος Εὐφρήταο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`978` ὃς δʼ ἤτοι πρῶτον μὲν ἀπʼ οὔρεος Ἀρμενίοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`979` μακρὸς ἐπὶ νότον εἶσι, πάλιν δʼ, ἀγκῶνας ἑλίξας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`980` ἄντκν ἠελίοιο μέσην Βαβυλῶνα περήσας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`981` Περσίδος εἰς ἁλὸς οἶδμα θοὴν ἀπερεύγεται ἄχνην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`982` ὑστατίῃς προχοῇσι Τερηδόνος ἐγγὺς ὁδεύων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`983` Τὸν δὲ μέτʼ εἰς αὐγὰς ποταμῶν ὤκιστος ἁπάντων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`984` Τίγρις ἐϋρρείτης φορέει ῥόον ἶσον ἐλαύνων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`985` τόσσον ἄνευθεν ἐὼν, ὅσον ἕβδομον ἦμαρ ὁδεύσας
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`986` ἴφθιος καὶ κραιπνὸς ἀνὴρ ἀνύσειεν ὁδίτης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`987` Ἔστι δέ τις κατὰ μέσσα περίτροχος ὕδασι λίμνη,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`988` οὕνομα Θωνῖτις, ἧς ἕλκεται ἐς μυχὰ Τίγρις,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`989` δύνων πολλὸν ἔνερθε· πάλιν δʼ ἐξαῦτις ἀνασχὼν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`990` ὀξύτερον προΐησι κάτω ῥόον· οὐκ ἂν ἐκείνου
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`991` ἐν πᾶσιν ποταμοῖσι θοώτερον ἄλλον ἶδοιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`992` Ὅσσῃ δʼ Εὐφρήτου καὶ Τίγριος ἔνδοθι γαῖα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`993` τήνδε περικτίονες μέσσην ποταμῶν ἐνέπουσιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`994` Οὐ μέντοι κείνης γε νομοὺς ὠνόσσατο βούτης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`995` οὐδʼ ὅστις, σύριγγι κερώνυχα Πᾶνα γεραίρων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`996` μήλοις ἀγραύλοισιν ἐφέσπεται· οὐδὲ μὲν ὕλην
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`997` παντοίην φυτοεργὸς ἀνὴρ ἀθερίσσατο καρπῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`998` τοίη ἐπεὶ κείνης ἄροσις πέλει, ἐν μὲν ἀέξειν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`999` ποίην, ἐν δέ νομοὺς εὐανθέας, ἐν δὲ καὶ ἀνδρῶν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1000` φύτλην καλλίστην τε καὶ ἀθανάτοισιν ὁμοίην.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1001` Τῆς μέν πρὸς βορέην λιπαρὴν χθόνα ναιετάουσιν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1002` ἀνέρες Ἀρμένιοί τε καὶ ἀγχέμαχοι Ματιηνοί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1003` οὔρεσι κεκλιμένοι, ποταμοῦ πρόπαρ Εὐφρήταο, πᾶσαν
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1004` πίονες ἀφνειοί τε καὶ Ἄρεος εὖ δεδαῶτες.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1005` Πρὸς δὲ νότον Βαβυλὼν ἱερὴ πόλις, ἥν ῥά τε
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1006` τείχεσιν ἁρραγέεσσι Σεμίραμις ἐστεφάνωσεν·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1007` αὐτὰρ ἐπʼ ἀκροπόληι μέγαν δόμον εἵσατο Βήλῳ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1008` χρσσῷ τʼ ἡδʼ ἐλέφαντι καὶ ἀργύρῳ ἀσκήσασα.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1009` Καὶ τῆς τοι πεδίον περιώσιον, ἔνθα τε πολλοὶ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1010` ἀκρόκομοι φοίνικες ἐπηρεφέες πεφύασιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1011` Ναὶ μὴν καὶ χρυσοῖο φέρει χαριέστερον ἄλλο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1012` ὑγρῆς βηρύλλου γλαυκὴν λίθον, ἣ περὶ χῶρον
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1013` φύεται ἐν προβολῆς ὀφιήτιδος ἔνδοθι πέτρης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1014` Αὐτὰρ ὁπὲρ Βαβυλῶνος ἐπὶ πνοιὴν βορέαο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1015` Κισσοὶ Μεσσαβάται τε Χαλωνῖταί τε νέμονται·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1016` ἀλλʼ ὁπότʼ Ἀρμενίων ὀρέων προπάροιθεν ὁδεύσῃς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1017` εἰς αὐγὰς, τότʼ ἔπειτα τὰ Μηδικὰ τέμπεα δήεις.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1018` Τῶν πρὸς μέν βορέην ἐριθηλέα γαῖαν ἔχουσι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1019` Τηλοί τε Μάρδοι τε καὶ ἀνέρες Ἀτροπατηνοί.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1020` Πρὸς δὲ νότον ναίουσιν ἀγαυῶν ἔθνεα Μήδων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1021` κείνης τοι γενεῆς ἐρικυδέος ἐκγεγαῶτες
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1022` Αἰήταο θυγατρὸς, ἀμύμονος ἡρωίνης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1023` Εὖτε γὰρ Ἀκταίοιο παρὰ ῥόον Ἰλισσοῖς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1024` φάρμακʼ ἐμήσατο λυγρὰ γόνῳ Πανδιονίδαο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1025` αἰδοῖ μὲν χῶρον κεῖνον λίπεν, ἐς δὲ βαθεῖαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1026` πλαζομένη κατὰ φῶτας, ὁμώνυμον ἵκετο γαῖαν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1027` οὐ μὲν ἑκὰς Κόλχων· Κόλχωνγε μὲν αἶαν ἱκέσθαι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1028` οὔ οἱ ἔην· μῆνιν γὰρ ἑοῦ δειδίσσετο πατρός.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1029` Τοὔνεκεν εἰσέτι νῦν πολυφάρμακοι ἄνδρες ἔασι
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1030` χώρην ναιετάοντες ἀπείριτον, οἱ μὲν ἐπʼ αὐτὰς
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1031` πέτρας, αἳ φύουσιν ἀφεγγέα ναρκισσίτην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1032` οἱ δʼ ἑκὰς ἐν λασίησι νενασμένοι εἰαμενῇσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1033` πώεα καλὰ νέμοντες, ἄδην βεβριθότα μαλλοῖς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1034` τόσσον ἐπ’ ἀντολίην τετραμμένοι, ἄχρι πυλάων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1035` Κασπιάδων, αἳτʼ εἰσὶ βαθυνομένας ὑπὸ πέτρας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1036` κληῖδες γαίης Ἀσιήτιδος, ᾗχι κέλευθος
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1037` ἐκτέταται βορέηνδε καὶ ἐς νότον ἐρχομένοισιν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1038` ἡ μὲν ἐς Ὑρκανίους, ἡ δʼ οὔρεα Περσίδος αἴης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1039` Ἀλλʼ ἤτοι πυλέων μὲν ὑπαὶ πόδα Κασπιάων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1040` Πάρθοι ναιετάουσιν ἀρήιοι, ἀγκυλότοξοι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1041` παντοίου πολέμοιο δαήμονες· οὐ γὰρ ἀρότρῳ
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1042` αὔλακ ἐπιθύνουσι, διασχίζοντες ἀρούρας,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1043` οὐδὲ μὲν ἐν νήεσσιν ἅλα τμήγουσιν ἐρετμοῖς,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1044` οὐδὲ νομῷ φέρβουσι βοῶν γένος· ἐκ δὲ γενέθλης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1045` νηπίαχοι τόξοισι καὶ ἱπποσύνησι μέλονται,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1046` αἰεὶ δʼ ἠχήεσσαν ἀνὰ χθόνα δοῦπος ἀκόντων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1047` ἢ βελέων, πάντη δέ τʼ ἀελλοπόδων δρόμος ἵππων
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1048` θυνόντων· οὐ γάρ σφι θέμις δόρποιο πάσασθαι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1049` πρὶν πολέμου μόχθοισι κάρην ἱδρῶτι παλῦναι·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1050` φέρβονται δʼ ἄγρῃσι δορικτήτου βιότοιο·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1051` ἀλλʼ ἔμπης κατὰ δῆριν ἀμαιμακέτους περ ἐόντας
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1052` Αὐσονίου βασιλῆος ἐπεπρήϋνεν ἀκωκή.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1053` Εἰ δέ σε καὶ Πέρσας ἰδέειν γλυκὺς ἵμερος αἱρεῖ,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1054` εὐφραδέως ἄν σοι καὶ τῶν γένος αὐδήσαιμι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1055` καὶ πόρον ἀενάων ποταμῶν, ὀρέων τε κελεύθους.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1056` Μοῦνοι γάρ τʼ Ἀσίης βασιλεύτατον ἔθνος ἔχουσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1057` μοῦνοι δʼ ἄσπετον ὄλβον ἐνὶ μεγάροισιν ἔθεντο,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1058` ὁππότε Μῃονίην καὶ Σάρδιας ἐξαλάπαξαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1059` Χρύσεά τοι κείνων μὲν ἐπὶ χροῒ τεύχεα φωτῶν,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1060` χρύσεα δʼαὖθʼ ἵπποισιν ἐπὶ στομάτεσσι χαλινά,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1061` χρυσῷ δʼ ἀμφὶ πόδεσσιν ἐκοσμήσαντο πέδιλα
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1062` τόσσος γάρ σφισιν ὄλβος ἀπείριτος· ἀλλά τοι εἴη
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1063` Περσὶς ὅλη μεγάλοισι περίδρομος οὔρεσι γαῖα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1064` Κασπιάδων πυλέων νοτιώτερον οἶμον ἔχουσα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1065` ἑλκομένη καὶ μέχρις ὁμωνύμου ἀμφιτρίτης.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1066` Τριχθὰ δέ μιν ναίουσι διασταδὸν, οἱ μὲν ὑπʼ ἄρκτους
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1067` τοξοφόρων σκιεροῖσι παρήμενοι οὔρεσι Μήδων,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1068` οἱ δὲ μεσήπειροι, οἱ δʼ ἐς νότον ἄχρι θαλάσσης·
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1069` πρῶτα Σάβαι, μετὰ τοὺς δὲ Πασαργάδαι, ἄγχι δὲ Τασκοί,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1070` ἄλλοι θʼ, οἳ ναίουσι διάνδιχα Περσίδα γαῖαν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1071` Καὶ τὴν μὲν πολέες ποταμοὶ περιπιαίνουσι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1072` τῇ καὶ τῇ σκολιῇσιν ἐλαυνόμενοι προχοῇσι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1073` Χωρὶς μὲν Κόρος ἐστὶ μέγας, χωρὶς δὲ Χοάσπης,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1074` ἕλκων Ἰνδὸν ὕδωρ, παρά τε ῥείων χθόνα Σούσων.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1075` Τὸῦ δʼ ἂν ἐπὶ πλευρῇσιν ἴδοις εὐωπὸν Ἀχάτην,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1076` κείμενον οἷα κύλινδρον ἐπὶ χθονὸς, ὅν ῥ’ ἀπὸ πέτρης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1077` χειμερίου ποταμοῖο κάτω σύρουσι χαράδραι.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1078` Αἰεὶ δ αὖ λιαροῖο γεγηθότες ἐξ ἀνέμοιο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1079` καρποὶ τηλεθάουσιν ἐπήτριμοι ἀλλήλοισιν.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1080` Φράζεο δʼ εἰς αὐγὰς λοιπὸν πόρον Ἀσίδος αἴης
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1081` ἐγγύθι γάρ τοι πέζα τελείεται ἠπείροιο.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1082` Ἤτοι μὲν παρὰ χεῦμα τὸ Περσικὸν Ὠκεανοῖο
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1083` Καρμανοὶ ναίουσιν ὑπʼ ἠελίῳ ἀνιόντι,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1084` Περσίδος οὐκ ἀπάνευθε διάνδιχα γαῖαν ἔχοντες,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1085` οἱ μὲν ὑπειράλιοι, τοὶ δʼ ἔνδοθεν ἠπειρῶται.
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::

:::: {.columns}

::: {.column width="60%"}
`1086` Τῶν δὲ πρὸς ἀντολίην Γεδρωσῶν ἕλκεται αἶα,
:::

::: {.column width="10%"}
:::

::: {.column width="25%" .sidenote}
:::

::::
