---
title: "Strabo 1.1"
---


## Reading selection 1


*Strabo defines geography as a both a pragmatic and scholarly study, and names Homer as its point of origin.*

### Selections from Strabo book 1, chapter 1

*Strabo 1.1.1-1.1.3*

::: {.columns}

::: {.column width="40%"}
**τῆς τοῦ φιλοσόφου πραγματείας** εἶναι νομίζομεν, εἴπερ ἄλλην τινά, καὶ τὴν γεωγραφικήν, ἣν νῦν **προῃρήμεθα** ἐπισκοπεῖν.
:::

::: {.column width="10%"}
:::

::: {.column width="40%" .sidenote}

**τῆς τοῦ φιλοσόφου πραγματείας**  *πραγματεία* routinely describes the activity of the scholar; for Strabo, that person is a *φιλόσοφος*. **προῃρήμεθα** from προαιρέω (imperfect tense).

:::
::::



:::: {.columns}

::: {.column width="40%"}
 ὅτι δ' οὐ φαύλως νομίζομεν ἐκ πολλῶν **δῆλον**: οἵ τε γὰρ πρῶτοι θαρρήσαντες αὐτῆς ἅψασθαι τοιοῦτοί τινες ὑπῆρξαν, **Ὄμηρός** τε καὶ **Ἀναξίμανδρος** ὁ Μιλήσιος καὶ **Ἑκαταῖος**, ὁ πολίτης αὐτοῦ, καθὼς καὶ ̓Ερατοσθένης φησί: καὶ **Δημόκριτος** δὲ καὶ **Εὔδοξος** καὶ **Δικαίαρχος** καὶ **Ἔφορος** καὶ ἄλλοι πλείους: ἔτι δὲ οἱ μετὰ τούτους,**Ἐρατοσθένης** τε καὶ **Πολύβιος** καὶ **Ποσειδώνιος**, ἄνδρες φιλόσοφοι.

:::

::: {.column width="10%"}
:::


::: {.column width="40%" .sidenote}

**δῆλον** δῆλον (ἐστί understood). The subject is the entire clause introduced by ὅτι. **Ὄμηρός… Ἀναξίμανδρος… Εκαταῖος… Δημόκριτος… Εὔδοξος… Δικαίαρχος…  ̓́Εφορος… .̓Ερατοσθένης… Πολύβιος…  Ποσειδώνιος** a chronologically ordered list of all the major geographers before Strabo -- all of them φιλόσοφοι. Strabo will review each in turn in books 1 and 2.
:::
::::
 

:::: {.columns}

::: {.column width="40%"} 
  ἥ τε πολυμάθεια, δι' ἧς μόνης ἐφικέσθαι τοῦδε τοῦ ἔργου **δυνατόν**, **οὐκ ἄλλου τινός ἐστιν ἢ** τοῦ τὰ θεῖα καὶ τὰ ἀνθρώπεια ἐπιβλέποντος, ὧνπερ τὴν φιλοσοφίαν ἐπιστήμην φασίν.
:::

::: {.column width="10%"}
:::

::: {.column width="40%" .sidenote}
**δυνατόν** δυνατόν (ἐστί understood) **οὐκ ἄλλου τινός ἐστιν ἢ** "is (a characteristic) of no other person than…"
:::
::::




:::: {.columns}

::: {.column width="40%"} 
  ὡς δ' αὕτως καὶ **ἡ ὠφέλεια** ποικίλη τις οὖσα, ἡ μὲν πρὸς τὰ πολιτικὰ καὶ τὰς ἡγεμονικὰς πράξεις, ἡ δὲ πρὸς ἐπιστήμην τῶν τε οὐρανίων καὶ τῶν ἐπὶ γῆς καὶ θαλάττης ζῴων καὶ φυτῶν καὶ καρπῶν καὶ τῶν ἄλλων ὅσα ἰδεῖν παρ' ἑκάστοις ἔστι, **τὸν αὐτὸν ὑπογράφει ἄνδρα**, τὸν φροντίζοντα τῆς περὶ τὸν βίον τέχνης καὶ εὐδαιμονίας.
:::

::: {.column width="10%"}
:::


::: {.column width="40%" .sidenote}
**ἡ ὠφέλεια… τὸν αὐτὸν ὑπογράφει ἄνδρα** The main subject-verb-object construction expands on the preceding idea: not only is *πολυμάθεια* characteristic of the philosopher; its usefulness for practical as well as scientific ends "outlines" or "sketches" the same man.  **ἄνδρα** Strabo sees philosophy as a gendered pursuit.

:::


::::  


:::: {.columns}

::: {.column width="40%"} 
αναλαβόντες δὲ **καθ' ἕκαστον ἐπισκοπῶμεν** τῶν εἰρημένων ἔτι μᾶλλον. 
:::

::: {.column width="10%"}
:::

::: {.column width="40%" .sidenote}

**καθ' ἕκαστον** "Item by item", "in more detail". **ἐπισκοπῶμεν**  from ἐπισκοπέω; the indicative would be ἐπισκοποῦμεν. What mood is this?


:::


::::



:::: {.columns}

::: {.column width="40%"} 
καὶ πρῶτον ὅτι **ὀρθῶς** **ὑπειλήφαμεν** καὶ ἡμεῖς καὶ οἱ πρὸ ἡμῶν, ὧν ἐστι καὶ ̔́Ιππαρχος, ἀρχηγέτην εἶναι **τῆς γεωγραφικῆς ἐμπειρίας**  ̔́Ομηρον, **ὃς οὐ μόνον** ἐν τῇ κατὰ τὴν ποίησιν ἀρετῇ πάντας **ὑπερβέβληται** τοὺς πάλαι καὶ τοὺς ὕστερον,  ἀλλὰ σχεδόν τι καὶ **τῇ κατὰ τὸν βίον ἐμπειρίᾳ** τὸν πολιτικόν,
:::

::: {.column width="10%"}
:::

::: {.column width="40%" .sidenote}
**ὀρθῶς** **ὑπειλήφαμεν** ὀρθῶς is scholarly Greek: it refers to a correct conclusion. (The noun κατόρθωσις is a correction of an error.) ὑπολαμβάνω (perfect active) is a normal verb to mean "taking a position" in a debate. Here it introduces an indiect statement. **τῆς γεωγραφικῆς ἐμπειρίας** The reader has conceded that geography has both practical benefits as well as purely scientific ones, so Strabo can turn to the founder of *geographic experience*, Homer.  **ὃς οὐ μόνον… ὑπερβέβληται** Scientific Greek prose can be as challenging as English; this is a massive relative clause. Its verb is ὑπερβέβληται from ὑπερβάλλω. Strabo uses the perfect because references to texts always emphasize their presentness, with either the present tense ("Homer says...") or as here "Homer has surpassed..." (and the Greek perfect makes clear that we feel the present effect of that excellence). **τῇ κατὰ τὸν βίον ἐμπειρίᾳ** τῇ ἐμπειρίᾳ is parallel to τῇ ἀρετῇ: no one would contest that Homer surpasses all others in the ἀρετή of his poetry; Strabo add that he is equally supreme in his practical knowledge (ἐμπειρία). Note that parallel attributive expressions with κατά (excellence in poetry paralled by experience in life).  τὸν πολιτικόν is in attributive position with τὸν βίον. The word order is not the most common. Is Strabo (playfully?) being just a little poetic in his expression?


:::
::::


:::: {.columns}
::: {.column width="40%"} 
 **ἀφ' ἧς** οὐ μόνον περὶ τὰς πράξεις ἐσπούδασεν ἐκεῖνος, **ὅπως** ὅτι πλείστας **γνοίη καὶ παραδώσει** τοῖς ὕστερον ἐσομένοις, ἀλλὰ καὶ τὰ περὶ τοὺς τόπους τούς τε καθ' ἕκαστα καὶ τοὺς κατὰ σύμπασαν **τὴν οἰκουμένην γῆν τε καὶ θάλατταν**: 
:::

::: {.column width="10%"}
:::

::: {.column width="40%" .sidenote}
 **ἀφ' ἧς** The subordination deepens with another relative clause. Antecedent of ἧς is ἐμπειρίᾳ. **ὅπως… γνοίη καὶ παραδώσει** Textbooks may tell you that ὅπως + optative is normal for purpose expressions after a past-time verb (secondary sequence), and ὅπως + future indicative for primary sequence verbs, but Strabo uses both here. Homer paid serious attention to (human) actions in order to know and understand them (optative γνοίη, a clear echo of the opening lines of the *Odyssey*); he also strove to transmit these deeds to those still to come. The indicative suggests a more vivid, present image or stronger effort. Homer is an epic poet and historian. (Consult Prof. Joseph on the interaction of these genres in Latin poetry and historiography.)  **τὴν οἰκουμένην γῆν τε καὶ θάλατταν** The proper concern of geography is with the part of the globe that humans inhabit.
:::

::::

:::: {.columns}

::: {.column width="40%"} 
οὐ γὰρ **ἂν** μέχρι τῶν ἐσχάτων αὐτῆς περάτων **ἀφίκετο** τῇ μνήμῃ κύκλῳ περιιών.
:::

::: {.column width="10%"}
:::

::: {.column width="40%" .sidenote}
**ἂν… ἀφίκετο** Aorist indicative from ἀφικνέομαι; apodosis of a past contrafactual condition.
:::

::::




:::: {.columns}
::: {.column width="40%"} 
καὶ πρῶτον μὲν τῷ ὠκεανῷ **περίκλυστον, ὥσπερ ἔστιν, ἀπέφαινεν αὐτήν**: ἔπειτα δὲ τῶν χωρίων τὰ μὲν ὠνόμαζε τὰ δὲ ὑπῃνίττετο τεκμηρίοις τισί, Λιβύην μὲν καὶ Αἰθιοπίαν καὶ Σιδονίους καὶ ̓Ερεμβούς, οὓς εἰκὸς λέγειν Τρωγλοδύτας ̓́Αραβας, ῥητῶς λέγων, τοὺς δὲ πρὸς ταῖς ἀνατολαῖς καὶ δύσεσιν αἰνιττόμενος ἐκ τοῦ τῷ ὠκεανῷ κλύζεσθαι: ἐντεῦθεν γὰρ **ἀνίσχοντα** ποιεῖ τὸν ἥλιον καὶ **δυόμενον** εἰς τοῦτον, ὡς δ' αὕτως καὶ τὰ ἄστρα καὶ τοὺς ἀστέρας **λελουμένους** ἐξ ὠκεανοῦ λέγει.
:::

::: {.column width="10%"}
:::


::: {.column width="40%" .sidenote}
**περίκλυστον… ἀπέφαινεν αὐτήν** Indirect statement; understand εἶναι. The first topic geographers must address is the shape of the inhabitted earth's forms.  **ἀνίσχοντα ποιεῖ τὸν ἥλιον… δυόμενον… ὡς δ' αὕτως καὶ τὰ ἄστρα καὶ τοὺς ἀστέρας λελουμένους… λέγει**
:::
::::


*Strabo 1.1.11*:

:::: {.columns}

::: {.column width="40%"}
νυνὶ δὲ ὅτι μὲν ̔́Ομηρος τῆς γεωγραφίας ἦρξεν, **ἀρκείτω** τὰ λεχθέντα. **φανεροὶ** δὲ καὶ οἱ ἐπακολουθήσαντες αὐτῷ ἄνδρες **ἀξιόλογοι καὶ οἰκεῖοι φιλοσοφίας**, ὧν τοὺς πρώτους μεθ' ̔́Ομηρον δύο φησὶν ̓Ερατοσθένης, ̓Αναξίμανδρόν τε Θαλοῦ γεγονότα γνώριμον καὶ πολίτην καὶ ̔Εκαταῖον τὸν Μιλήσιον: **τὸν μὲν** οὖν ἐκδοῦναι πρῶτον γεωγραφικὸν πίνακα, **τὸν δὲ** ̔Εκαταῖον καταλιπεῖν **γράμμα**, πιστούμενον ἐκείνου εἶναι ἐκ τῆς ἄλλης αὐτοῦ **γραφῆς**.
:::

::: {.column width="10%"}
:::


::: {.column width="40%" .sidenote}
**ἀρκείτω** 3rd person imperative. Neuter plural subjects (τὰ λεχθέντα) always take a singular finite form. **φανεροὶ… ἀξιόλογοι καὶ οἰκεῖοι φιλοσοφίας** Understand εἰσίν. Homer's immediate followers are conspicuously notable philosophers. ἀξιόλογος ("worth recording") is an echo of Herotodus; οἰκεῖοι φιλοσοφίας "members of the house of philosophy". **τὸν μὲν… τὸν δὲ** Anaximander and Thales are also are the first scholars to tackle the most fundamental jobs of geographic study: creating a graphic model of the earth as a map, and describing the earth in a textual treatise. **γράμμα** γράμμα and **γραφή** both derive from γράφω, "mark, draw a line." γράμμα here refers to a textual document; γραφή is a drawing, or map. A treatise (γράμμα) is attributed to Hecataeus because of its resemblance to his second or subsequent map (τῆς ἄλλης γραφῆς) after Anaximander. 
:::

::::
