---
title: "Introduction to Strabo"
---


## Strabo: introduction

We begin with selections from the *Geography* of Strabo of Amasia (a town in Asia Minor). Strabo composed his *magnum opus* in 17 books at around the time of the Emperor Augustus, at the end of the first century BCE and beginning of the first century CE. As was customary with scholarly (and especially with scientific) treatises, Strabo's programmatic introduction begins by defining the subject matter of his discipline, along with major topics and goals of its study, then systematically reviews the work of his predecessors, especially where, in Strabo's view, they need correcting. This occupies the first two books of the *Geography*. Books 3 through 17 then give a description of the inhabited world, moving systematically in a great clockwise sweep from Spain in the west, eastward across Europe and into northern Asia, before finally coming westward back across southern Asia and Africa to the Atlantic coast.

Perhaps surprisingly to a modern reader, a central question running throughout Strabo's first two books is whether Homer should be considered a scientific geographer. In the Hellenistic period, the Greek study of geography had been revolutionized, not only by expanded geographic knowledge, but also by the application of scientific mathematical methods. Eratosthenes of Cyrene (in northern Africa) in particular had used geometric calculations to estimate the circumference of the Earth in the third century BCE, and arrived at a figure that would not be rivaled in its accuracy for 2000 years.

Eratosthenes clearly believed that the work of his own generation inaugurated a new scientific kind of study (in Greek, an ἐπιστήμη). His disdain for the view that Homer was the starting point of all knowledge is best illustrated in a memorable one-liner reported by Strabo himself (Strabo 1.2.15):


:::: {.columns}

::: {.column width="50%"}
> φησὶ τότ' ἂν εὑρεῖν τινα ποῦ  ̓Οδυσσεὺς πεπλάνηται, ὅταν εὕρῃ τὸν σκυτέα τὸν συρράψαντα τὸν τῶν ἀνέμων ἀσκόν.
:::

::: {.column width="50%"}
>He (*Eratosthenes*) says that a person would find where Odysseus wandered when he finds the leather worker who stitched together the bag of the winds.
:::
::::

Strabo energetically presents the counter argument. (In fact, most of book 2 is given over to a critique of Eratosthenes' views.) The result is unique in ancient literature: an extended discussion of how to read poetic texts as scholarly works, presented in prose that assiduously adheres to the vocabulary and syntax of contemporary technical writing.





